// This source code is a part of Project Violet.
// Copyright (C) 2020-2024. violet-team. Licensed under the Apache-2.0 License.

class Artists {
  static Map<Map<String, dynamic>, dynamic> collection = {
    //
    //  Masculine Artists
    //
    {'default': 'COMIC快楽天', 'ko': '코믹 쾌락천', 'ja': 'COMIC快楽天'}: [
      'homunculus',
      'hamao',
      'tosh',
      'napata',
      'hisasi',
      //
      'konchiki',
      'redrop',
      'okara',
      'minato fumi',
      'sumiya',
      'ishikawa shisuke',
      'shono kotaro',
      'azuma ran',
      //
      'misagi nagomu',
      'inuburo',
      'bosshi',
      'e-musu aki',
      'koume keito',
      'itou eight',
      'higenamuchi',
      'namboku',
      //
      'azuma tesshin',
      'bareisho',
      'pon takahanada',
      'onda chiro',
      'hachiya makoto',
      'naruko hanaharu',
      'linda',
      'miyabi tsuzuru',
      'mg joe',
      'nishi iori',
    ],
    {'default': 'COMIC X-EROS', 'ko': '코믹 제로스'}: [
      'distance',
      'yonekura kengo',
      'tsukino jyogi',
      'fuetakishi',
      'ishikei',
      'oda non',
      'takayaki',
      'knuckle curve',
      'hisakawa tinn',
      'makinosaka shinichi',
      'kuronomiki',
      'akino sora',
      'gomennasai',
      'sasayuki',
      '23',
      'shindol',
      'kurosaki rendou',
      'hiyoshi hana',
      'yarii shimeta',
      'shinonome ryu',
      'yoshida inuhito',
      'hori hiroaki',
    ],
    {'default': 'Pure Love', 'ko': '순애', 'ja': '純愛', 'zh': '爱'}: [
      'ichimatsu',
      'e-musu aki',
      'fujimaru',
      'hinasaki yo',
      'suihei sen',
      'momoko',
      'kizuka kazuki',
      'doumou',
      'katsurai yoshiaki',
      'hiten',
      'emily',
      'john k. pe-ta',
      'botan mochito',
      'meme50',
      'tomohiro kai',
      'sanjuurou',
      'yamada yuuya',
      'umakuchi_shouyu',
      'azuma tesshin',
      'meganei',
      'goban',
      'homunculus',
      'kamizuki shiki',
      'kotengu',
      'key',
      'ikuhana niro',
      'thikiso takeda',
      'kyockcho',
      'hamao',
      'mikuni_mizuki',
      'otabe sakura',
      'regdic',
      'akagi_asahito',
      'michiking',
      'pyon-kti',
      'kakao',
      'hinahara_emi',
    ],
    {'default': 'Loli', 'ko': '로리'}: [
      'quzilax',
      'mochi',
      'asanagi',
      'tanabe kyou',
      'tamagoro',
      'azuma sawayoshi',
      'kinnotama',
      'mitsudoue',
      'yone kinji',
      'dancyo',
      'kiya shii',
      'henreader',
      'misao.',
      'ohisashiburi',
      'kanyapyi',
      'yukiu con',
      'haguhagu',
      'maki',
      'hisasi',
      'noise',
      'kinku',
      'okada kou',
      'atage',
      'miwa futaba',
      'mamezou',
      'ichihaya',
      'tanaka decilitre',
      'kannazuki motofumi',
      'panbai',
      'fuyuno mikan',
      'gengorou',
      'shouji ayumu',
      'rico',
      'shimanto shisakugata',
      'yuizaki kazuya',
      'tamano kedama',
      'urajirou',
      'shirane taito',
      'usashiro mani',
      'gomennasai',
      'sekiya asami',
      'inuboshi',
      'higashiyama show',
    ],
    {'default': 'Oneshota', 'ko': '오네쇼타'}: [
      'nora higuma',
      'alto seneka',
      'amamitu kousuke',
      'morishima kon',
      'tonnosuke',
      'kakuzatou',
      'katou fuguo',
      'shuz',
      'nise',
      'joy',
      'okyuuri',
      'dhibi',
      'hasemi ryo',
      'himukai kyousuke',
      'kotoba ai',
      'shift',
      'tachibana omina',
      'achumuchi',
      'agata',
      'itou life',
      'ryo',
    ],
    {'default': 'Femdom', 'ko': '펨돔'}: [
      'hiroe rei',
      'takei ooki',
      'parabola',
      '2t',
      'akai mato',
      'mame',
      'oouso',
      'shindou',
      'hanabi',
    ],
    {'default': 'Hypnosis', 'ko': '최면'}: [
      'aiue oka',
      'chimosaku',
      'haitokukan',
      'hiyori hamster',
      'jude',
      'kodamashi',
      'peniken',
      'roche',
      'satou kuuki',
    ],
    {'default': 'Netorare', 'ko': '네토라레'}: [
      'taniguchi-san',
      'fuuga',
      'shimanto shisakugata',
      'akitsuki itsuki',
      'mizutani tooru',
      'katsurai yoshiaki',
      'yuzuki n dash',
      'kokudakaya',
      'zonda',
      'abe inori',
      'itou eight',
      'karasu',
      'hana hook',
      'carn',
      'matsukawa',
      'kino hitoshi',
      'mucha',
      'maguro coffee',
      'shioroku',
      'takatsu',
      'nagare ippon',
      'kikuichi monji',
      'sanagi torajirou',
      'shiki takuto',
      'tachikawa negoro',
      'norakuro nero',
      'munashimujou',
      'shinozuka yuuji',
      'tyranu',
      'yamamoto yammy',
      'tanaka aji',
      'yunioshi',
      'crowe',
      'yukiyoshi mamizu',
      'satou kuuki',
      'takeda hiromitsu',
      'takeda aranobu',
      'kemigawa',
      'nakajima yuka',
      'jingrock',
      'sannyuutei shinta',
      'nakajima yuka',
      'hana hook',
      'ame arare',
      'arakure',
      'hirari',
      'ayakase chiyoko',
      'bang-you'
    ],
    {'default': 'Exhibitionist', 'ko': '노출증'}: [
      'momota',
      'otabe sakura',
      'souryuu',
      'tsuttsu',
      'guglielmo',
      'kanzume',
    ],
    {'default': 'Harem', 'ko': '하렘'}: [
      'agata',
      'upa24',
      'tachibana omina',
      'diisuke',
      'akatsuki myuuto',
      'marui maru',
      'narusawa kei',
      'raita',
    ],
    {'default': 'Yuri', 'ko': '유리'}: [
      'nago',
      'yuniba',
      'deadnoodles',
      'funiai riko',
      'hidari kagetora',
      'romi',
      'seuma',
      'amaro tamaro',
      'asaka',
      'ishikawa naoya',
      'kanbayashi makoto',
      'kazuhito',
      'kurogane kenn',
      'mikanuji',
      'ooizumi daisaku',
      'orikuchi hirata',
      'miso tya',
      'mizuga',
      'wakadori nikomi',
      'yanagi hareta',
      'umekiti',
      'shichoson',
      'tadano kagekichi',
      'senyuu',
      'takahashi tetsuya',
      'toyosaki shu',
      'tyatubo',
    ],
    {'default': 'Milf', 'ko': '밀프'}: [
      'zero no mono',
      'aino chie',
      'ayakase chiyoko',
      'musashimaru',
      'tawara hiryuu',
      'karma tatsurou',
    ],
    {'default': 'ㅇㅅㅇ', 'ko': 'ㅇㅅㅇ'}: [
      'chacharan',
      'homura subaru',
      'motoyon',
    ],

    //
    //  Effeminate
    //
    {'default': 'Shota'}: [],

    //
    //  Gay
    //
    {'default': 'Gay', 'ko': '게이'}: [
      'tagame gengoroh',
    ],
    {'default': 'Yaoi', 'ko': '야오이'}: [
      'sakura siro',
      'shinagawa mikuzu',
      'scotch',
      'seihoukei',
      'aian',
      'aichi shiho',
      'takayamanon',
      'jairou',
      'kokonoe yomogi',
      'ttuunn',
      'binto',
      'collagen',
      'ikezaki misa',
      'ikujinashi no fetishist',
      'konayama kata',
      'locon',
      'menoko',
      'mucha',
      'ayato ayari',
      'kotoko',
      'urakuso',
      'bennys',
      'saikawa yusa',
      'inari',
      'takashi',
      'nemunemu',
      'palco nagashima',
      'gujira',
      'hokuro ryuseigun',
      'yoshiie',
      'tonikaku',
    ],

    //
    //  Minor
    //
    {'default': 'BDSM'}: [],
    {'default': 'Insect'}: [],
    {'default': 'Futanari', 'ko': '후타나리'}: [
      'c.r',
      'cevoy',
      'tefun',
      'tousen',
      'tyranu',
      'yokoshima takemaru',
      'hanamaki kaeru',
      'hidiri rei',
      'condessa',
      'junji',
      'alpha alf layla',
      'aomushi',
      'arata iri',
      'ax',
      'kichiku na eta',
      'kuga hajime',
      'messy',
      'piririnegi',
      'initsukkii',
      'itose ikuto',
      'rihito akane',
      'shido mayuru',
      'siooninco',
      'tamazatou',
    ],
    {'default': 'CG', 'ko': '컴퓨터 그래픽'}: [
      'abo manten',
      'abubu',
      'aim',
      'aka p',
      'akushizu',
      'almarosso',
      'astre',
      'azuki yui',
      'beesama',
      'beni bana',
      'bigfoot no mori',
      'blast',
      'butakoma 300g',
      'butcherboy',
      'cccpo',
      'cream gallon',
      'critical hit',
      'dl mate',
      'dr. vu',
      'drain',
      'engawa suguru',
      'eronamin h',
      'fujirin',
      'fukin',
      'fushigi dou',
      'fuzukikai',
      'gara ayuri nisshi',
      'gemuo',
      'harusame yuuki',
      'hatachi',
      'hikari club',
      'himukai kyousuke',
      'hiraru',
      'hukidamari',
      'iku',
      'inagita',
      'inu g',
      'joy ride',
      'kaiga',
      'katase aoko',
      'kawahagitei',
      'kawano masatoshi',
      'kemuri haku',
      'kiryu manzoku',
      'kishimen',
      'kokyu no heya',
      'kotera',
      'koto',
      'ktzw',
      'kurasaki aya',
      'm-keifu',
      'maki daikichi',
      'makomo ashino',
      'mama',
      'marubatsu bunko',
      'maruhage p',
      'mika sayaki',
      'militia',
      'milk force',
      'mimizu',
      'miso oden',
      'mochikuu usagi',
      'mokushi',
      'monaka',
      'munashimujou',
      'mushi',
      'myu-po',
      'nabeshiki',
      'nakura yumari',
      'nemunoya',
      'nyamota',
      'ogami kazuki',
      'onetouch',
      'p herb',
      'painpa',
      'pastel bitch',
      'pellagra',
      'pine',
      'pinkjoe',
      'potato',
      'prophecy',
      'rebe11',
      'redlight',
      'reitou mikan',
      'roche',
      'rororogi mogera',
      'russian neko',
      'ryokutya',
      'sage',
      'saipaco',
      'sakuragi rian',
      'sayryu',
      'shii',
      'shinobu',
      'shishimaru',
      'small dog',
      'someoka yusura',
      'soundvillage',
      'strange beast',
      'sueyuu',
      'sweetedda',
      'tam',
      'taniguchi daisuke',
      'tetsuo',
      'tohani',
      'toilet komoru',
      'toji',
      'tokyo corechica',
      'ts revolver',
      'urahushigi',
      'usuki',
      'v-mag',
      'vae',
      'yac',
      'yaomai',
      'yareba dekiru ko',
      'yodakapan',
      'yoko juusuke',
    ],
    {'default': 'Series', 'ko': '시리즈'}: [
      'artist:okunoha                    ',
      'group:chinjao girl.               ',
      'artist:yanagida fumita            ',
      'artist:hori hiroaki               ',
      'group:m                           ',
      'group:b.b.t.t.                    ',
      'group:fuka fuka                   ',
      'artist:mutsutake                  ',
      'group:dangan minorz               ',
      'artist:ishibashi shingo           ',
      'group:sandworks                   ',
      'group:pollinosis                  ',
      'artist:hinotsuki neko             ',
      'artist:waira                      ',
      'group:u.r.c                       ',
      'group:u.r.c                       ',
      'group:kaze no gotoku              ',
      'artist:ruri tsubame               ',
      'artist:maguro teikoku             ',
      'artist:mana                       ',
      'artist:kichirock                  ',
      'artist:kotoyoshi yumisuke         ',
      'group:ph-bu                       ',
      'group:bluemage                    ',
      'artist:ikuhana niro               ',
      'artist:shirota dai                ',
      'group:subesube1kg                 ',
      'group:super flat lolinitron       ',
      'artist:onizuka naoshi             ',
      'artist:arai kei                   ',
      'group:kansai orange               ',
      'group:dodo fuguri                 ',
      'artist:kusatsu terunyo            ',
      'group:izanagi                     ',
      'artist:mafuyu                     ',
      'group:amazake hatosyo-ten         ',
      'group:aoba q madou                ',
      'group:kamikadou                   ',
      'artist:morimiya masayuki          ',
      'group:kabayakiya                  ',
      'artist:otoo                       ',
      'artist:iapoc                      ',
      'artist:norinko                    ',
      'artist:itou eight                 ',
      'artist:leafy                      ',
      'group:metamor                     ',
      'artist:suzutsuki kurara           ',
      'group:s shoten                    ',
      'artist:mitsuki mantarou           ',
      'group:chibikko kingdom            ',
      'artist:tksn                       ',
      'artist:kitani sai                 ',
      'group:7-ban no okimono            ',
      'artist:kimimaru                   ',
      'group:omoshiro burger             ',
      'artist:kimimaru                   ',
      'group:akausagi                    ',
      'artist:meme50                     ',
      'group:lunatic prophet             ',
      'artist:yoshiki                    ',
      'artist:taniguchi-san              ',
      'group:horizontal world            ',
      'artist:mamezou                    ',
      'artist:drill jill                 ',
      'artist:jino                       ',
      'artist:vanilla                    ',
      'group:graygreed                   ',
      'group:esora note                  ',
      'group:mikan dou                   ',
      'group:yokohama junky              ',
      'artist:hatomugi                   ',
      'artist:charu                      ',
      'artist:tachibana yuu              ',
      'artist:sasahara yuuki             ',
      'group:ptd                         ',
      'artist:kloah                      ',
      'group:butakoma 300g               ',
      'group:mugicha.                    ',
      'group:saz                         ',
      'artist:henrybird                  ',
      'group:extended part               ',
      'group:kurocan                     ',
      'artist:momoya show-neko           ',
      'artist:yamamoto zenzen            ',
      'artist:momoya show-neko           ',
      'artist:sian                       ',
      'group:key trash                   ',
      'artist:inu                        ',
      'artist:kakao                      ',
      'group:n.s craft                   ',
      'artist:kanno takanori             ',
      'group:on-show                     ',
      'artist:makari tohru               ',
      'artist:makari tohru               ',
      'artist:kurosu gatari              ',
      'artist:sarfata                    ',
      'artist:kiasa                      ',
      'artist:suishin tenra              ',
      'group:hatake no oniku             ',
      'artist:urakan                     ',
      'artist:alp                        ',
      'artist:jackasss                   ',
      'artist:alp                        ',
      'group:mag kan                     ',
      'artist:oda non                    ',
      'artist:kahlua suzuki              ',
      'artist:kakyouin chiroru           ',
      'artist:inue shinsuke              ',
      'artist:zunta                      ',
      'artist:ashiomi masato             ',
      'group:kuroyuki                    ',
      'group:shotaian                    ',
      'artist:emons                      ',
      'artist:nisino                     ',
      'group:chocolate cube              ',
      'artist:namidame                   ',
      'group:hooliganism                 ',
      'artist:mojarin                    ',
      'artist:v-mag                      ',
      'group:poyopacho                   ',
      'artist:izumi                      ',
      'artist:mikaduki neko              ',
      'artist:gomabura                   ',
      'artist:murasaki syu               ',
      'artist:henkuma                    ',
      'group:potato salad                ',
      'group:miyamaya                    ',
      'artist:kon-kit                    ',
      'group:paranoia cat                ',
      'artist:tachibana omina            ',
      'group:mikan dou                   ',
      'artist:tachibana omina            ',
      'group:lemonmaiden                 ',
      'group:noraneko-no-tama            ',
      'group:ruiketsuan                  ',
      'artist:sanjiro                    ',
      'artist:reizei                     ',
      'group:sigma-arts                  ',
      'group:ameshoo                     ',
      'artist:b-curd                     ',
      'group:hitsuji-1ban-shibori        ',
      'group:hitsuji-1ban-shibori        ',
      'group:mtsp                        ',
      'artist:mizu                       ',
      'group:rodiura.                    ',
      'artist:manami tatsuya             ',
      'artist:akino sora                 ',
      'artist:shindol                    ',
      'group:daihonei                    ',
      'artist:dairoku tenmaou great      ',
      'artist:distance                   ',
      'group:fuzukikai                   ',
      'artist:kakugari kyoudai           ',
      'group:shoujo kishidan             ',
      'artist:mashiraga aki              ',
      'artist:hyji                       ',
      'artist:takaryoo                   ',
      'artist:satsuki itsuka             ',
      'group:shimapan                    ',
      'group:petapan                     ',
      'artist:sanom                      ',
      'artist:azuma yuki                 ',
      'artist:minamoto                   ',
      'artist:jairou                     ',
      'artist:bajou takurou              ',
      'artist:sahara wataru              ',
      'artist:ment                       ',
      'artist:sindoll                    ',
      'group:tail spot                   ',
      'group:type-57                     ',
      'group:kuzunoha                    ',
      'group:ultra siccative             ',
      'artist:ootsuka mahiro             ',
      'artist:asahina hikage             ',
      'artist:ogadenmon                  ',
      'group:niku ringo                  ',
      'group:magono-tei                  ',
      'artist:tsumetoro                  ',
      'group:odin                        ',
      'group:plant                       ',
      'artist:urekemo lala               ',
      'group:erdelied                    ',
      'artist:alexi laiho                ',
      'artist:motsuaki                   ',
      'artist:kurokawa izumi             ',
      'artist:urekemo lala               ',
      'group:gust                        ',
      'group:nimunoya                    ',
      'artist:ayano naoto                ',
      'artist:yd                         ',
      'group:osaru no noumiso            ',
      'artist:nanao                      ',
      'artist:tamagoro                   ',
      'artist:yanagi yuu                 ',
      'group:creayus                     ',
      'group:metamor                     ',
      'artist:rocket monkey              ',
      'artist:amakuchi                   ',
      'artist:hiyoshi hana               ',
      'artist:yuyama chika               ',
      'artist:hiyoshi hana               ',
      'group:kansai orange               ',
      'artist:nagiyama                   ',
      'group:kansai orange               ',
      'group:subesube1kg                 ',
      'artist:rangetsu                   ',
      'group:ame nochi yuki              ',
      'artist:shinobe                    ',
      'group:minshuku inarimushi         ',
      'artist:motomiya mitsuki           ',
      'artist:arai kei                   ',
      'group:b.b.t.t.                    ',
      'artist:arai kei                   ',
      'artist:koyanagi royal             ',
      'group:m                           ',
      'group:titokara 2nd branch         ',
      'group:buffalow propaganda         ',
      'group:raijinkai                   ',
      'artist:yumano yuuki               ',
      'group:ciaociao                    ',
      'group:kodoku intelligence         ',
      'artist:hisasi                     ',
      'group:furaipan daimaou            ',
      'artist:jin                        ',
      'group:jitaku vacation             ',
      'artist:umiushi                    ',
      'artist:nimuno                     ',
      'group:neko gosho                  ',
      'artist:koppe                      ',
      'group:cool brain                  ',
      'artist:kim toxic                  ',
      'artist:ryo                        ',
      'artist:arimura yuu                ',
      'artist:napata                     ',
      'artist:chouchin ankou             ',
      'artist:abbb                       ',
      'artist:saikawa yusa               ',
      'artist:chuuka naruto              ',
      'artist:katsurai yoshiaki          ',
      'artist:zone                       ',
      'artist:iruma kamiri               ',
      'artist:nakagami takashi           ',
      'artist:hitsuji hako               ',
      'artist:hitsuji hako               ',
      'group:ocarina                     ',
      'artist:makio                      ',
      'artist:kenbouka                   ',
      'artist:kekocha                    ',
      'artist:shindou                    ',
      'artist:yuzuki n dash              ',
      'artist:yuzuki n dash              ',
      'artist:kuromotokun                ',
      'artist:kamino ryu-ya              ',
      'artist:nyuu                       ',
      'artist:kemosuke                   ',
      'artist:lime                       ',
      'artist:silinder                   ',
      'artist:itaba hiroshi              ',
      'artist:akatsuki myuuto            ',
      'artist:syuuen                     ',
      'group:arubain                     ',
      'artist:leonat                     ',
      'artist:akatsuki myuuto            ',
      'artist:fumihiko                   ',
      'group:studio parm                 ',
      'artist:ogami kazuki               ',
      'artist:narita kyousha             ',
      'group:kaiki nisshoku              ',
      'artist:michiking                  ',
      'artist:nori-haru                  ',
      'artist:kino hitoshi               ',
      'group:cyclone                     ',
      'group:p-collection                ',
      'artist:mizutani tooru             ',
      'group:cyclone                     ',
      'artist:araki kanao                ',
      'group:nakayohi mogudan            ',
      'artist:mizuiro megane             ',
      'group:shinjugai                   ',
      'artist:shinonome ryu              ',
      'artist:rokuku                     ',
      'artist:aoi manabu                 ',
      'artist:oyari ashito               ',
      'group:da hootch                   ',
      'artist:shijima                    ',
      'group:ikkizuka                    ',
      'group:frac                        ',
      'artist:wakamatsu                  ',
      'artist:michiking                  ',
      'group:jinsei yokosuberi.          ',
      'artist:kiai neko                  ',
      'group:hlz                         ',
      'group:saigado                     ',
      'artist:fan no hitori              ',
      'artist:futamine kobito            ',
      'group:sakekan memorial            ',
      'artist:ameto yuki                 ',
      'group:crank.in                    ',
      'artist:eba                        ',
      'artist:fan no hitori              ',
      'artist:tokie hirohito             ',
      'artist:frunbell                   ',
      'artist:kiya shii                  ',
      'artist:miwa futaba                ',
      'artist:takenoko seijin            ',
      'artist:shouji nigou               ',
      'artist:ohmi takeshi               ',
      'artist:mgmee                      ',
      'group:mayoineko                   ',
      'artist:mutsumi masato             ',
      'artist:sho-yan                    ',
      'artist:asakura blue               ',
      'group:goo-paaa                    ',
      'artist:higata akatsuki            ',
      'group:kamogawaya                  ',
      'group:mousou bijutsubu            ',
      'group:konohanaya                  ',
      'artist:keno yantarou              ',
      'artist:ootsuka kotora             ',
      'artist:izayoi seishin             ',
      'artist:yuiga naoha                ',
      'artist:mameko                     ',
      'artist:takayuki hiyori            ',
      'group:nayuta no hakobune          ',
      'group:nanimoshinai                ',
      'artist:nakajima yuka              ',
      'group:archives                    ',
      'artist:pu2                        ',
      'artist:as109                      ',
      'artist:zucchini                   ',
      'artist:inanaki shiki              ',
      'artist:gust-san                   ',
      'group:studio a                    ',
      'group:jyouren kishidan            ',
      'artist:ayane                      ',
      'artist:kyockcho                   ',
      'group:ribi dou                    ',
      'artist:mizuryu kei                ',
      'artist:type.90                    ',
      'artist:tenro aya                  ',
      'group:listless time               ',
      'group:metro notes                 ',
      'artist:sirofugu                   ',
      'artist:sasamori tomoe             ',
      'artist:sasamori tomoe             ',
      'artist:yukino minato              ',
      'artist:mool                       ',
      'artist:sasamori tomoe             ',
      'artist:yukino minato              ',
      'group:trodh                       ',
      'artist:alto seneka                ',
      'artist:rusty soul                 ',
      'group:d-baird                     ',
      'artist:momoko                     ',
      'artist:fujiwara shunichi          ',
      'group:moco chouchou               ',
      'artist:oshare kyoushitsu.         ',
      'artist:kotobuki utage             ',
      'artist:toguchi masaya             ',
      'artist:spacezin                   ',
      'artist:fukudahda                  ',
      'artist:ookuma nekosuke            ',
      'artist:momoyama jirou             ',
      'artist:hechi                      ',
      'artist:aoi mikku                  ',
      'artist:hamao                      ',
      'artist:riki                       ',
      'artist:kiyomiya ryo               ',
      'artist:kurauda shouta             ',
      'group:alpha to yukaina nakamatachi',
      'artist:yukiu con                  ',
      'artist:kuga hajime                ',
      'group:otaku beam                  ',
      'artist:tatsunami youtoku          ',
      'artist:shishikura sendou          ',
      'group:kenja time                  ',
      'artist:bekotarou                  ',
      'artist:type.90                    ',
      'group:reflection                  ',
      'group:digital lover               ',
      'group:real                        ',
      'group:hobukuro                    ',
      'group:kusari                      ',
      'artist:as109                      ',
      'artist:haruhisky                  ',
      'artist:nakajima yuka              ',
      'artist:kuon michiyoshi            ',
      'artist:kihiru                     ',
      'artist:hazuki kaoru               ',
      'artist:midori no rupe             ',
      'artist:asaki takayuki             ',
      'artist:nenemaru                   ',
      'artist:ooshima ryou               ',
      'group:toadstool factory           ',
      'artist:hota.                      ',
      'artist:komiya yuuta               ',
      'artist:kiriyama taichi            ',
      'group:saigado                     ',
      'artist:hankotsu max               ',
      'artist:alpha                      ',
      'group:chocolate land              ',
      'group:shinjugai                   ',
      'group:sirius.                     ',
      'artist:poruno ibuki               ',
      'group:nisemididoronokai           ',
      'artist:oyari ashito               ',
      'artist:michiking                  ',
      'artist:cuzukago                   ',
      'group:pianiishimo                 ',
      'group:flying chicken              ',
      'artist:hoshino ryuichi            ',
      'group:naruho-dou                  ',
      'group:cyclone                     ',
      'artist:hiryuu ran                 ',
      'artist:pija                       ',
      'artist:schulz                     ',
      'group:nosebleed                   ',
      'group:project harakiri            ',
      'group:nagaredamaya                ',
      'artist:tukinowagamo               ',
      'artist:kurona                     ',
      'artist:yuzuki n dash              ',
      'artist:rage                       ',
      'group:tj studio                   ',
      'artist:hakaba yodomu              ',
      'group:crimson comics              ',
      'group:hikari club                 ',
      'artist:chuuka naruto              ',
      'artist:chuuka naruto              ',
      'artist:kakao                      ',
      'artist:chuuka naruto              ',
      'group:40010 1-go                  ',
      'group:crimson comics              ',
      'group:akiyama production          ',
      'group:world lover                 ',
      'group:nanatsu no kagiana          ',
      'artist:tsurui                     ',
      'group:23.4do                      ',
      'artist:jin                        ',
      'artist:canape                     ',
      'group:nyuu koubou                 ',
      'group:kodoku intelligence         ',
      'artist:saigado                    ',
      'artist:saigado                    ',
      'artist:ulrich                     ',
      'group:lunatic maiden              ',
      'group:nama cream biyori           ',
      'artist:morishima kon              ',
      'group:ins-mode                    ',
      'artist:kagura moromi              ',
      'artist:azuse                      ',
      'artist:kouzuki rio                ',
      'artist:gemuo                      ',
      'artist:arai kei                   ',
      'artist:oyster                     ',
      'artist:rustle                     ',
      'group:royal bitch                 ',
      'artist:kishizuka kenji            ',
      'group:pandaniku                   ',
      'artist:higashiyama show           ',
      'artist:kurosawa kiyotaka          ',
      'artist:tetsuna                    ',
      'artist:otono natsu                ',
      'group:kansai orange               ',
      'group:type-g                      ',
      'artist:amanagi seiji              ',
      'artist:haruki genia               ',
      'group:kurosawa pict               ',
      'artist:hitotose rin               ',
      'artist:satsuki neko               ',
      'artist:kiichi                     ',
      'artist:kenkou cross               ',
      'group:number2                     ',
      'artist:miyanogi jiji              ',
      'group:nwa                         ',
      'group:miyubi                      ',
      'group:ezokuroten                  ',
      'group:kimuchi-tei                 ',
      'artist:kamogawa tanuki            ',
      'artist:kidmo                      ',
      'group:mieow                       ',
      'artist:rokkaku yasosuke           ',
      'artist:hisama kumako              ',
      'group:hiiro no kenkyuushitsu      ',
      'artist:takasugi kou               ',
      'artist:reizei                     ',
      'artist:distance                   ',
      'artist:shimanto shisakugata       ',
      'artist:akino sora                 ',
      'artist:kasuga mayu                ',
      'artist:homunculus                 ',
      'artist:namaniku atk               ',
      'artist:homunculus                 ',
      'artist:kiasa                      ',
      'artist:yukisaki miale             ',
      'artist:hatachi                    ',
      'artist:mogudan                    ',
      'artist:homare                     ',
      'group:suzu no oka                 ',
      'artist:hitoi                      ',
      'group:haruharudo                  ',
      'artist:kinnotama                  ',
      'artist:mimic                      ',
      'artist:okunoha                    ',
      'artist:ohara makoto               ',
      'artist:mutsutake                  ',
      'artist:nagare ippon               ',
      'artist:yamamoto zenzen            ',
      'artist:musashimaru                ',
      'artist:soborogo                   ',
      'artist:crimson                    ',
      'artist:benantoka                  ',
      'artist:uo denim                   ',
      'group:athome shuka                ',
      'artist:aoi masami                 ',
      'group:kouzukitei                  ',
      'group:abgrund                     ',
      'group:hannama                     ',
      'group:nisemididoronokai           ',
      'group:aomizuan                    ',
      'group:lunatic maiden              ',
      'artist:derauea                    ',
      'artist:akino sora                 ',
      'artist:rocket monkey              ',
      'artist:clone ningen               ',
      'artist:kurosu gatari              ',
      'artist:warabino matsuri           ',
      'artist:malcorond                  ',
      'artist:tanabe kyou                ',
      'artist:endou okito                ',
      'artist:simon                      ',
      'artist:poruno ibuki               ',
      'group:purimomo                    ',
      'group:alpha to yukaina nakamatachi',
      'artist:takashi                    ',
      'artist:toji                       ',
      'group:polinky hiroba              ',
      'artist:sanbun kyoden              ',
      'artist:batsu                      ',
      'artist:zutta                      ',
      'artist:motsuaki                   ',
      'artist:motsuaki                   ',
      'artist:herio                      ',
      'artist:yukiyoshi mamizu           ',
      'artist:anma                       ',
      'artist:katou jun                  ',
      'group:wada mountain               ',
      'artist:uousaoh                    ',
      'group:sound sticker               ',
      'group:f taku                      ',
      'artist:kamizuki shiki             ',
      'artist:mameojitan                 ',
      'artist:nagiyama                   ',
      'artist:nanao                      ',
      'artist:nanao                      ',
      'group:kuroyuki                    ',
      'artist:nanao                      ',
      'artist:gujira                     ',
      'artist:huqu                       ',
      'group:hooliganism                 ',
      'group:kaminendo.corporation       ',
      'artist:fuetakishi                 ',
      'group:shoot the moon              ',
      'group:global one                  ',
      'artist:kakyouin chiroru           ',
      'artist:quzilax                    ',
      'group:potato house                ',
      'artist:chaccu                     ',
      'artist:kirisaki byakko            ',
      'artist:tonikaku                   ',
      'group:angelphobia                 ',
      'artist:bakugatou                  ',
      'artist:takei ooki                 ',
      'artist:kaishaku                   ',
      'artist:mashiraga aki              ',
      'artist:ratatatat74                ',
      'artist:naruhodo                   ',
      'artist:umu rahi                   ',
      'artist:maro                       ',
      'artist:clover                     ',
      'artist:kanyapyi                   ',
      'group:nagiyamasugi                ',
      'artist:nakasone haiji             ',
      'artist:orico                      ',
      'artist:abyo4                      ',
      'artist:tamagoro                   ',
      'artist:tamagoro                   ',
      'artist:arino hiroshi              ',
      'artist:ishigaki takashi           ',
      'artist:kizuka kazuki              ',
      'artist:guglielmo                  ',
      'group:egao ga ichiban             ',
      'group:studio big-x                ',
      'group:sweettaboo                  ',
      'artist:tana                       ',
      'artist:okada kou                  ',
      'artist:nishizaki eimu             ',
      'artist:saigado                    ',
      'artist:usuki                      ',
      'group:supe                        ',
      'group:sweettaboo                  ',
      'artist:murian                     ',
      'artist:tsuyatsuya                 ',
      'artist:accio                      ',
      'artist:fue                        ',
      'group:micro page                  ',
      'group:nyuu koubou                 ',
      'artist:akatsuki myuuto            ',
      'artist:narusawa kei               ',
      'artist:evs                        ',
      'group:behind moon                 ',
      'artist:izurumi                    ',
      'artist:gozz                       ',
      'artist:tagame gengoroh            ',
      'artist:alpha                      ',
      'artist:goyac                      ',
      'group:eromazun                    ',
      'artist:mogg                       ',
      'group:askray                      ',
      'group:shigunyan                   ',
      'artist:monaim                     ',
      'group:alice no takarabako         ',
      'group:hamusuta-nonikomi           ',
      'artist:shigunyan                  ',
      'artist:getty                      ',
      'group:aodouhu                     ',
      'artist:ooyun                      ',
      'group:fukazume kizoku             ',
      'artist:q                          ',
      'artist:u-hi                       ',
      'group:doll play                   ',
      'artist:tanishi                    ',
      'group:hamusuta-nonikomi           ',
      'group:nakasone battalion          ',
      'artist:yanagawa rio               ',
      'group:mimoneland                  ',
      'artist:neromashin                 ',
      'group:iv va shin                  ',
      'artist:mikihime                   ',
      'group:yuunabe shinkouchuu         ',
      'group:nakayohi                    ',
      'artist:sanjuurou                  ',
      'artist:nakani                     ',
      'artist:as-special                 ',
      'group:rpg company 2               ',
      'group:joshinzoku                  ',
      'group:amamitu hakushi             ',
      'artist:takaku toshihiko           ',
      'artist:arekusa mahone             ',
      'group:fakestar                    ',
      'artist:type.90                    ',
      'group:eroe                        ',
      'group:otonano do-wa               ',
      'group:takakuya                    ',
      'artist:bak hyeong jun             ',
      'artist:hanauna                    ',
      'artist:azuma sawayoshi            ',
      'artist:bak hyeong jun             ',
      'artist:mikoshiro honnin           ',
      'artist:bosshi                     ',
      'artist:mizuryu kei                ',
      'artist:nishimaki tohru            ',
      'artist:tomohiro kai               ',
      'artist:nanase meruchi             ',
      'artist:creeeen                    ',
      'artist:mikuni mizuki              ',
      'artist:akame                      ',
      'artist:ichiri                     ',
      'group:abgrund                     ',
      'group:kiyosumi hurricane          ',
      'artist:okumori boy                ',
      'group:karakishi youhei-dan        ',
      'artist:amamitu kousuke            ',
      'artist:fukuyama naoto             ',
      'group:circle heron                ',
      'group:hapoi-dokoro                ',
      'artist:kishizuka kenji            ',
      'group:royal bitch                 ',
      'group:algolagnia                  ',
      'artist:mojarin                    ',
      'artist:dammit                     ',
      'artist:izumi                      ',
      'group:archf                       ',
      'group:eroe                        ',
      'group:nakayohi mogudan            ',
      'artist:paja                       ',
      'artist:nico pun nise              ',
      'artist:mimonel                    ',
      'group:showa saishuu sensen        ',
      'artist:mda starou                 ',
      'artist:itto                       ',
      'artist:cuvie                      ',
      'artist:zero no mono               ',
      'group:hi-per pinch                ',
      'artist:fuetakishi                 ',
      'artist:toumi haruka               ',
      'artist:saikawa yusa               ',
      'artist:ma-kurou                   ',
      'artist:nekomata naomi             ',
      'artist:shindol                    ',
      'artist:takaharu                   ',
      'artist:seto yuuki                 ',
      'artist:akazawa red                ',
      'group:arekusa thunder             ',
      'artist:date                       ',
      'group:shoot the moon              ',
      'group:mentaiko                    ',
      'artist:kink                       ',
      'group:kuronisiki                  ',
      'artist:shiramayumi                ',
      'group:shiroganean                 ',
      'artist:ikuhana niro               ',
      'artist:kino hitoshi               ',
      'group:nyuu koubou                 ',
      'artist:byman                      ',
      'artist:kawahagitei                ',
      'artist:ohtomo takuji              ',
      'artist:piero                      ',
      'group:takanaedoko                 ',
      'artist:miharu                     ',
      'artist:nanakagi satoshi           ',
      'artist:tatsuhiko                  ',
      'artist:okazaki takeshi            ',
      'artist:wanyanaguda                ',
      'artist:tomomimi shimon            ',
      'artist:takao yori                 ',
      'artist:kinoshita jiroh            ',
      'group:studio skb                  ',
      'artist:eba                        ',
      'artist:takanae kyourin            ',
      'group:bloody okojo                ',
      'artist:yui toshiki                ',
      'artist:yui toshiki                ',
      'artist:kira hiroyoshi             ',
      'group:team kihara                 ',
      'group:purin kai yoghurt           ',
      'artist:jin                        ',
      'group:monsieur                    ',
      'artist:kobayashi youkoh           ',
      'group:funi funi lab               ',
      'group:nama cream biyori           ',
      'artist:satou toshio               ',
      'artist:motomiya mitsuki           ',
      'artist:stealth changing line      ',
      'group:ninokoya                    ',
      'group:sankaku apron               ',
      'artist:sumiya                     ',
      'group:forbidden-lips              ',
      'group:ninokoya                    ',
      'artist:chiri                      ',
      'artist:tamagoro                   ',
      'group:hito no fundoshi            ',
      'artist:amaro tamaro               ',
      'group:xration                     ',
      'artist:drifter                    ',
      'group:kawaisounako                ',
      'group:goroujirou                  ',
      'artist:shindol                    ',
      'group:mtsp                        ',
      'artist:murasaki syu               ',
      'artist:kyockcho                   ',
      'group:frac                        ',
      'artist:mutsutake                  ',
      'artist:katou fuguo                ',
      'artist:ikuhana niro               ',
      'group:slapstickstrike             ',
      'artist:mil                        ',
      'artist:shono kotaro               ',
      'artist:yuzuki n dash              ',
      'artist:chiba tetsutarou           ',
      'artist:inuboshi                   ',
      'artist:locon                      ',
      'artist:ayasaka mitsune            ',
      'artist:ninoko                     ',
      'artist:sanbun kyoden              ',
      'artist:mizuryu kei                ',
      'group:fugudoku                    ',
      'artist:nanase meruchi             ',
      'artist:yukiu con                  ',
      'artist:nyuu                       ',
      'artist:8                          ',
      'artist:kimimaru                   ',
      'artist:nyoro nyorozou             ',
      'artist:mucha                      ',
      'group:wakuwaku doubutsuen         ',
      'artist:rin                        ',
      'artist:suzuki nago                ',
      'artist:cuvie                      ',
      'group:tanmatsu ijou               ',
      'artist:nori-haru                  ',
      'artist:abbb                       ',
      'artist:namonashi                  ',
      'group:small marron                ',
      'group:majimeya                    ',
      'artist:yuyu                       ',
      'artist:hanasaku mahiru            ',
      'artist:isao                       ',
      'artist:hyji                       ',
      'artist:shiratama                  ',
      'artist:nasipasuta                 ',
      'artist:taira hajime               ',
      'artist:ryo                        ',
      'artist:fujimoto gou               ',
      'group:haguruman                   ',
      'group:locker room                 ',
      'artist:satou chagashi             ',
      'group:nagomiyasan                 ',
      'artist:toriki kuuya               ',
      'artist:takunomi                   ',
      'artist:ooshima ryou               ',
      'artist:simon                      ',
      'artist:botan mochito              ',
      'artist:shono kotaro               ',
      'group:p-collection                ',
      'artist:ichino                     ',
      'artist:yurikawa                   ',
      'group:noraneko-no-tama            ',
      'artist:morishima kon              ',
      'artist:crimson                    ',
      'artist:hatokonro                  ',
      'group:alice no takarabako         ',
      'group:g-scan corp.                ',
      'group:cior                        ',
      'group:crimson comics              ',
      'artist:ogami wolf                 ',
      'artist:100yen locker              ',
      'artist:utu                        ',
      'group:big gym                     ',
      'artist:tennouji kitsune           ',
      'artist:mizone                     ',
      'group:magono-tei                  ',
      'artist:muk                        ',
      'group:kouhuku shigen              ',
      'artist:poyeop                     ',
      'group:nanimoshinai                ',
      'artist:haruhisky                  ',
      'artist:amagasa higasa             ',
      'artist:badhand                    ',
      'artist:koutarosu                  ',
      'artist:crimson                    ',
      'artist:kiduki erika               ',
      'artist:shiwasu no okina           ',
      'group:enuma elish                 ',
      'group:makuu gundan                ',
      'artist:soba                       ',
      'group:chroma of wall              ',
      'artist:shiokonbu                  ',
      'group:nanimoshinai                ',
      'artist:asakura kukuri             ',
      'group:saz                         ',
      'group:ryuknigthia                 ',
      'artist:yoshiura kazuya            ',
      'artist:shinozuka atsuto           ',
      'artist:fei                        ',
      'artist:ikoma ippei                ',
      'group:muchakai                    ',
      'artist:kazakura                   ',
      'artist:hozumi takashi             ',
      'artist:leopard                    ',
      'group:niku drill                  ',
      'group:gallery walhalla            ',
      'artist:kanoe                      ',
      'group:p-forest                    ',
      'artist:mikuni mizuki              ',
      'group:fugudoku                    ',
      'artist:rozer                      ',
      'group:dorepooru                   ',
      'artist:yasui riosuke              ',
      'artist:yukino minato              ',
      'artist:saitom                     ',
      'artist:tenchuumaru                ',
      'group:tenzan koubou               ',
      'group:tiba-santi                  ',
      'artist:sakamata nerimono          ',
      'group:otomekibun                  ',
      'artist:sasamori tomoe             ',
      'artist:chiba tetsutarou           ',
      'artist:midori no rupe             ',
      'artist:kemonono                   ',
      'artist:motsuaki                   ',
      'artist:minami star                ',
      'artist:michiking                  ',
      'group:yadokugaeru                 ',
      'artist:tamahagane                 ',
      'artist:nt00                       ',
      'group:kikurage-ya                 ',
      'artist:katou fuguo                ',
      'artist:ninoko                     ',
      'artist:saotome mokono             ',
      'artist:charu                      ',
      'artist:karory                     ',
      'group:funi funi lab               ',
      'group:harugoya                    ',
      'group:rokumonsen                  ',
      'group:valssu                      ',
      'artist:hanya                      ',
      'group:kazeuma                     ',
      'group:zettai shoujo               ',
      'artist:sansyoku amido.            ',
      'group:karomix                     ',
      'group:studio kimigabuchi          ',
      'artist:gustav                     ',
      'artist:higashiyama show           ',
      'artist:carn                       ',
      'artist:harusuke                   ',
      'artist:michiking                  ',
      'artist:amano ameno                ',
      'artist:someoka yusura             ',
      'artist:ken-1                      ',
      'artist:tatsunami youtoku          ',
      'artist:sasamori tomoe             ',
      'group:achromic                    ',
      'group:kazeuma                     ',
      'artist:aiue oka                   ',
      'artist:raita                      ',
      'artist:kikurage                   ',
      'artist:pon takahanada             ',
      'artist:minato fumi                ',
      'artist:toumasu                    ',
      'group:aquadrop                    ',
      'artist:minami star                ',
      'artist:akino sora                 ',
      'group:circle outerworld           ',
      'artist:mikami mika                ',
      'group:kajimura market             ',
      'group:shis                        ',
      'group:mieow                       ',
      'artist:rustle                     ',
      'artist:katsura airi               ',
      'artist:tamaoki benkyo             ',
      'artist:kajimura kajima            ',
      'artist:sekiya asami               ',
      'artist:tomisawa chinatsu          ',
      'artist:musouduki                  ',
      'artist:kaname aomame              ',
      'artist:heizo                      ',
      'artist:laliberte                  ',
      'group:ameshoo                     ',
      'group:fuzukikai                   ',
      'group:blue bean                   ',
      'artist:the jinshan                ',
      'artist:hazuki kaoru               ',
      'artist:ooyun                      ',
      'artist:kikunosukemaru             ',
      'artist:mikaduki neko              ',
      'group:werk                        ',
      'group:pochi-goya.                 ',
      'artist:yi hyeon min               ',
      'artist:pochi.                     ',
      'group:kyokutou koumuten           ',
      'group:toko-ya                     ',
      'artist:chiba shuusaku             ',
      'artist:kitoen                     ',
      'artist:takei masaki               ',
      'artist:charlie nishinaka          ',
      'artist:andou shuki                ',
      'group:rpg company 2               ',
      'artist:umu rahi                   ',
      'group:abarenbow tengu             ',
      'artist:izumi yuujiro              ',
      'artist:charu                      ',
      'artist:blackgg                    ',
      'artist:toumi haruka               ',
      'group:valssu                      ',
      'artist:namonashi                  ',
      'group:cat food                    ',
      'artist:ooyun                      ',
      'artist:hong banjang               ',
      'group:sankaku apron               ',
      'artist:karma tatsurou             ',
      'group:kamikadou                   ',
      'artist:fumitsuki sou              ',
      'artist:gao                        ',
      'artist:fantastic whale            ',
      'group:darabuchidou                ',
      'artist:ginyou haru                ',
      'artist:banssee                    ',
      'artist:darabuchi                  ',
      'group:angyadow                    ',
      'group:udon-ya                     ',
      'artist:suga hideo                 ',
      'artist:zan                        ',
      'artist:doppel                     ',
      'artist:solopipb                   ',
      'artist:shikei                     ',
      'artist:mx2j                       ',
      'artist:pinko                      ',
      'artist:kizuki aruchu              ',
      'artist:ramjak                     ',
      'artist:takeda hiromitsu           ',
      'group:marked-two                  ',
      'artist:yu geuk-jo                 ',
      'group:rubbish selecting squad     ',
      'group:fatalpulse                  ',
      'artist:sanbun kyoden              ',
      'artist:asanagi                    ',
      'artist:shiina                     ',
      'group:alemateorema                ',
      'artist:kobayashi youkoh           ',
      'group:mitarashi club              ',
      'artist:bak hyeong jun             ',
      'artist:mitarashi kousei           ',
      'artist:shikishiro konomi          ',
      'artist:juder                      ',
      'artist:worin                      ',
      'artist:z-ton                      ',
      'artist:luv p                      ',
      'group:i-raf-you                   ',
      'artist:butcherboy                 ',
      'artist:ryokutya                   ',
      'artist:son hee-joon               ',
      'group:digital lover               ',
      'artist:nakajima yuka              ',
      'group:clesta                      ',
      'artist:cle masahiro               ',
    ].reversed.toList()
  };
}
