// This source code is a part of Project Violet.
// Copyright (C) 2020. violet-team. Licensed under the Apache-2.0 License.

class Artists {
  static Map<Map<String, dynamic>, dynamic> collection = {
    //
    //  Masculine Artists
    //
    {'default': 'COMIC快楽天', 'ko': '코믹 쾌락천', 'ja': 'COMIC快楽天'}: [
      'homunculus',
      'hamao',
      'tosh',
      'napata',
      'hisasi',
      //
      'konchiki',
      'redrop',
      'okara',
      'minato fumi',
      'sumiya',
      'ishikawa shisuke',
      'shono kotaro',
      'azuma ran',
      //
      'misagi nagomu',
      'inuburo',
      'bosshi',
      'e-musu aki',
      'koume keito',
      'itou eight',
      'higenamuchi',
      'namboku',
      //
      'azuma tesshin',
      'bareisho',
      'pon takahanada',
      'onda chiro',
      'hachiya makoto',
      'naruko hanaharu',
      'linda',
      'miyabi tsuzuru',
      'mg joe',
      'nishi iori',
    ],
    {'default': 'COMIC X-EROS', 'ko': '코믹 제로스'}: [
      'distance',
      'yonekura kengo',
      'tsukino jyogi',
      'fuetakishi',
      'ishikei',
      'oda non',
      'takayaki',
      'knuckle curve',
      'hisakawa tinn',
      'makinosaka shinichi',
      'kuronomiki',
      'akino sora',
      'gomennasai',
      'sasayuki',
      '23',
      'shindol',
      'kurosaki rendou',
      'hiyoshi hana',
      'yarii shimeta',
      'shinonome ryu',
      'yoshida inuhito',
      'hori hiroaki',
    ],
    {'default': 'Pure Love', 'ko': '순애', 'ja': '純愛', 'zh': '爱'}: [
      "ichimatsu",
      "e-musu aki",
      "fujimaru",
      "hinasaki yo",
      "suihei sen",
      "momoko",
      "kizuka kazuki",
      "doumou",
      "katsurai yoshiaki",
      "hiten",
      "emily",
      "john k. pe-ta",
      "botan mochito",
      "meme50",
      "tomohiro kai",
      "sanjuurou",
      "yamada yuuya",
      "umakuchi_shouyu",
      "azuma tesshin",
      "meganei",
      "goban",
      "homunculus",
      "kamizuki shiki",
      "kotengu",
      "key",
      "ikuhana niro",
      "thikiso takeda",
      "kyockcho",
      "hamao",
      "mikuni_mizuki",
      "otabe sakura",
      "regdic",
      "akagi_asahito",
      "michiking",
      "pyon-kti",
      "kakao",
      "hinahara_emi",
    ],
    {'default': 'Loli', 'ko': '로리'}: [
      'quzila',
      'mochi',
      'asanagi',
      "tanabe kyou",
      "tamagoro",
      "azuma sawayoshi",
      "kinnotama",
      "mitsudoue",
      "yone kinji",
      'dancyo',
      'kiya shii',
      'henreader',
      "misao.",
      "ohisashiburi",
      'kanyapyi',
      'yukiu con',
      'haguhagu',
      'maki',
      'hisasi',
      'noise',
      'kinku',
      'okada kou',
      'atage',
      'miwa futaba',
      'mamezou',
      'ichihaya',
      'tanaka decilitre',
      'kannazuki motofumi',
      'panbai',
      'fuyuno mikan',
      'gengorou',
      'shouji ayumu',
      'rico',
      'shimanto shisakugata',
      'yuizaki kazuya',
      'tamano kedama',
      "urajirou",
      'shirane taito',
      'usashiro mani',
      'gomennasai',
      'sekiya asami',
      'inuboshi',
      'higashiyama show',
    ],
    {'default': 'Oneshota', 'ko': '오네쇼타'}: [
      'nora higuma',
      'alto seneka',
      'amamitu kousuke',
      "morishima kon",
      'tonnosuke',
      'kakuzatou',
      'katou fuguo',
      'shuz',
      'nise',
      'joy',
      'okyuuri',
      'dhibi',
      'hasemi ryo',
      'himukai kyousuke',
      'kotoba ai',
      'shift',
      "tachibana omina",
      'achumuchi',
      'agata',
      'itou life',
      'ryo',
    ],
    {'default': 'Femdom', 'ko': '펨돔'}: [
      "hiroe rei",
      "takei ooki",
      "parabola",
      "2t",
      "akai mato",
      "mame",
      "oouso",
      "shindou",
      "hanabi",
    ],
    {'default': 'Hypnosis', 'ko': '최면'}: [
      'aiue oka',
      'chimosaku',
      'haitokukan',
      'hiyori hamster',
      'jude',
      'kodamashi',
      'peniken',
      'roche',
      'satou kuuki',
    ],
    {'default': 'Netorare', 'ko': '네토라레'}: [
      "taniguchi-san",
      "fuuga",
      "shimanto shisakugata",
      "akitsuki itsuki",
      "mizutani tooru",
      'katsurai yoshiaki',
      'yuzuki n dash',
      'kokudakaya',
      'zonda',
      'abe inori',
      'itou eight',
      'karasu',
      'hana hook',
      'carn',
      'matsukawa',
      'kino hitoshi',
      'mucha',
      'maguro coffee',
      'shioroku',
      'takatsu',
      'nagare ippon',
      'kikuichi monji',
      'sanagi torajirou',
      'shiki takuto',
      'tachikawa negoro',
      'norakuro nero',
      'munashimujou',
      'shinozuka yuuji',
      'tyranu',
      'yamamoto yammy',
      'tanaka aji',
      'yunioshi',
      'crowe',
      'yukiyoshi mamizu',
      'satou kuuki',
      'takeda hiromitsu',
      'takeda aranobu',
      'kemigawa',
      'nakajima yuka',
      'jingrock',
      'sannyuutei shinta',
      'nakajima yuka',
      'hana hook',
      'ame arare',
      'arakure',
      'hirari',
      'ayakase chiyoko',
      'bang-you'
    ],
    {'default': 'Exhibitionist', 'ko': '노출증'}: [
      'momota',
      'otabe sakura',
      'souryuu',
      'tsuttsu',
      'guglielmo',
      'kanzume',
    ],
    {'default': 'Harem', 'ko': '하렘'}: [
      'agata',
      'upa24',
      'tachibana omina',
      'diisuke',
      'akatsuki myuuto',
      'marui maru',
      'narusawa kei',
      'raita',
    ],
    {'default': 'Yuri', 'ko': '유리'}: [
      'nago',
      'yuniba',
      'deadnoodles',
      'funiai riko',
      'hidari kagetora',
      'romi',
      'seuma',
      'amaro tamaro',
      'asaka',
      'ishikawa naoya',
      'kanbayashi makoto',
      'kazuhito',
      'kurogane kenn',
      'mikanuji',
      'ooizumi daisaku',
      'orikuchi hirata',
      'miso tya',
      'mizuga',
      'wakadori nikomi',
      'yanagi hareta',
      'umekiti',
      'shichoson',
      'tadano kagekichi',
      'senyuu',
      'takahashi tetsuya',
      'toyosaki shu',
      'tyatubo',
    ],
    {'default': 'Milf', 'ko': '밀프'}: [
      'zero no mono',
      'aino chie',
      'ayakase chiyoko',
      'musashimaru',
      'tawara hiryuu',
      'karma tatsurou',
    ],
    {'default': 'ㅇㅅㅇ', 'ko': 'ㅇㅅㅇ'}: [
      'chacharan',
      'homura subaru',
      'motoyon',
    ],

    //
    //  Effeminate
    //
    {'default': 'Shota'}: [],

    //
    //  Gay
    //
    {'default': 'Gay', 'ko': '게이'}: [
      "tagame gengoroh",
    ],
    {'default': 'Yaoi', 'ko': '야오이'}: [
      'sakura siro',
      'shinagawa mikuzu',
      'scotch',
      'seihoukei',
      'aian',
      'aichi shiho',
      'takayamanon',
      'jairou',
      'kokonoe yomogi',
      'ttuunn',
      'binto',
      'collagen',
      'ikezaki misa',
      'ikujinashi no fetishist',
      'konayama kata',
      'locon',
      'menoko',
      'mucha',
      'ayato ayari',
      'kotoko',
      'urakuso',
      'bennys',
      'saikawa yusa',
      'inari',
      'takashi',
      'nemunemu',
      'palco nagashima',
      'gujira',
      'hokuro ryuseigun',
      'yoshiie',
      'tonikaku',
    ],

    //
    //  Minor
    //
    {'default': 'BDSM'}: [],
    {'default': 'Insect'}: [],
    {'default': 'Futanari', 'ko': '후타나리'}: [
      'c.r',
      'cevoy',
      'tefun',
      'tousen',
      'tyranu',
      'yokoshima takemaru',
      'hanamaki kaeru',
      'hidiri rei',
      'condessa',
      'junji',
      'alpha alf layla',
      'aomushi',
      'arata iri',
      'ax',
      'kichiku na eta',
      'kuga hajime',
      'messy',
      'piririnegi',
      'initsukkii',
      'itose ikuto',
      'rihito akane',
      'shido mayuru',
      'siooninco',
      'tamazatou',
    ],
    {'default': 'CG', 'ko': '컴퓨터 그래픽'}: [
      'abo manten',
      'abubu',
      'aim',
      'aka p',
      'akushizu',
      'almarosso',
      'astre',
      'azuki yui',
      'beesama',
      'beni bana',
      'bigfoot no mori',
      'blast',
      'butakoma 300g',
      'butcherboy',
      'cccpo',
      'cream gallon',
      'critical hit',
      'dl mate',
      'dr. vu',
      'drain',
      'engawa suguru',
      'eronamin h',
      'fujirin',
      'fukin',
      'fushigi dou',
      'fuzukikai',
      'gara ayuri nisshi',
      'gemuo',
      'harusame yuuki',
      'hatachi',
      'hikari club',
      'himukai kyousuke',
      'hiraru',
      'hukidamari',
      'iku',
      'inagita',
      'inu g',
      'joy ride',
      'kaiga',
      'katase aoko',
      'kawahagitei',
      'kawano masatoshi',
      'kemuri haku',
      'kiryu manzoku',
      'kishimen',
      'kokyu no heya',
      'kotera',
      'koto',
      'ktzw',
      'kurasaki aya',
      'm-keifu',
      'maki daikichi',
      'makomo ashino',
      'mama',
      'marubatsu bunko',
      'maruhage p',
      'mika sayaki',
      'militia',
      'milk force',
      'mimizu',
      'miso oden',
      'mochikuu usagi',
      'mokushi',
      'monaka',
      'munashimujou',
      'mushi',
      'myu-po',
      'nabeshiki',
      'nakura yumari',
      'nemunoya',
      'nyamota',
      'ogami kazuki',
      'onetouch',
      'p herb',
      'painpa',
      'pastel bitch',
      'pellagra',
      'pine',
      'pinkjoe',
      'potato',
      'prophecy',
      'rebe11',
      'redlight',
      'reitou mikan',
      'roche',
      'rororogi mogera',
      'russian neko',
      'ryokutya',
      'sage',
      'saipaco',
      'sakuragi rian',
      'sayryu',
      'shii',
      'shinobu',
      'shishimaru',
      'small dog',
      'someoka yusura',
      'soundvillage',
      'strange beast',
      'sueyuu',
      'sweetedda',
      'tam',
      'taniguchi daisuke',
      'tetsuo',
      'tohani',
      'toilet komoru',
      'toji',
      'tokyo corechica',
      'ts revolver',
      'urahushigi',
      'usuki',
      'v-mag',
      'vae',
      'yac',
      'yaomai',
      'yareba dekiru ko',
      'yodakapan',
      'yoko juusuke',
    ],
  };
}
