//===----------------------------------------------------------------------===//
//
//                       Violet Tag Info Program
//
//===----------------------------------------------------------------------===//
//
//  Copyright (C) 2021. violet-team. All Rights Reserved.
//
//===----------------------------------------------------------------------===//

const kor_tag = {
  'uploader': '업로더',
  'female': '여성',
  'male': '남성',
  'tag': '태그',
  'lang':'언어',
  'language':'언어',
  'series': '시리즈',
  'artist': '작가',
  'uploader': '업로더',
  'character':'캐릭터',
  'type': '타입',
  'class': '클래스',
  'recent': '최근',
  'random': '랜덤',
  'korean': '한국어',
  'japanese': '일본어',
  'english': '영어',
  'spanish': '스페인어',
  'thai': '태국어',
  'german': '독일어',
  'chinese': '중국어',
  'portuguese': '포루투갈어',
  'french':'프랑스어',
  'tagalog': '타갈로그어',
  'russian': '러시아어',
  'italian': '이탈리아어',
  'polish': '폴란드어',
  'vietnamese': '베트남어',
  'hungarian': '헝가리어',
  'czech': '체코어',
  'indonessian': '인도네시안어',
  'arabic': '아랍어',

  'doujinshi': '동인지',
  'artist cg': '아티스트 CG',
  'game cg': '게임 CG',
  'group': '그룹',
  'mosaic censorship': '모자이크 검열',
  'incest': '근친',
  'full color': '풀컬러',
  'tankoubon': '단행본',
  'ffm threesome': '여여남 쓰리썸',
  'full censorship': '완전 검열',
  'mmf threesome': '남남여 쓰리썸',
  'story arc': '스토리 아크',
  'uncensored': '미검열',
  'multi-work series': '시리즈물',
  'anthology': '시집',
  'replaced': '대체됨',
  'webtoon': '웹툰',
  'incomplete': '미완성',
  'scanmark': '스캔 마크',
  'sample': '샘플',
  'rewrite': '재작성',
  'novel': '소설',
  'animated': '애니',
  'artbook': '아트북',
  'body swap': '신체교환',
  'out of order': '정리되지 않음',
  'time stop': '시간 정지',
  'missing cover': '커버 없음',
  'monster': '몬스터',
  'mtf threesome': '남여트젠 쓰리썸',
  '3d': '3D',
  'twins': '쌍둥이',
  'ttm threesome': '남트젠트젠 쓰리썸',
  'compilation': '모음집',
  'oyakodon': '모녀덮밥',
  'poor grammar': '맞춤법 안맞음',
  'watermarked': '워터마크',
  'mmt threesome': '남남트젠 쓰리썸',
  'comedy': '코미디',
  'frottage': '프로타주',
  'horror': '호러',
  'manga': '망가',
  'female:beauty mark': 'female:애교점',
  'female:gloves': 'female:장갑',
  'female:big breasts': 'female:거유',
  'female:loli': 'female:로리',
  'female:stockings': 'female:스타킹',
  'female:schoolgirl uniform': 'female:여학생 교복',
  'female:sole female': 'female:단독여성',
  'female:anal': 'female:애널',
  'female:nakadashi': 'female:질내 사정',
  'female:bondage': 'female:속박',
  'female:blowjob': 'female:펠라치오',
  'female:rape': 'female:강간',
  'female:glasses': 'female:안경',
  'female:ahegao': 'female:아헤가오',
  'female:paizuri': 'female:파이즈리',
  'female:defloration': 'female:첫 경험',
  'female:double penetration': 'female:동시 삽입',
  'female:milf': 'female:밀프',
  'female:sex toys': 'female:섹스 토이',
  'female:futanari': 'female:후타나리',
  'female:x-ray': 'female:투시',
  'female:swimsuit': 'female:수영복',
  'female:yuri': 'female:백합',
  'female:femdom': 'female:펨돔',
  'female:tentacles': 'female:촉수',
  'female:impregnation': 'female:수정',
  'female:sister': 'female:여동생',
  'female:netorare': 'female:네토라레',
  'female:pregnant': 'female:임신',
  'female:pantyhose': 'female:팬티 스타킹',
  'female:mind break': 'female:타락',
  'female:lactation': 'female:수유',
  'female:dark skin': 'female:검은 피부',
  'female:collar': 'female:목걸이',
  'female:footjob': 'female:풋잡',
  'female:maid': 'female:메이드',
  'female:big ass': 'female:큰 엉덩이',
  'female:bikini': 'female:비키니',
  'female:cheating': 'female:불륜',
  'female:urination': 'female:방뇨',
  'female:catgirl': 'female:고양이 소녀',
  'female:gag': 'female:개그',
  'female:masturbation': 'female:자위',
  'female:handjob': 'female:핸드잡',
  'female:exhibitionism': 'female:노출증',
  'female:garter belt': 'female:가터 벨트',
  'female:mind control': 'female:최면',
  'female:huge breasts': 'female:거대한 가슴',
  'female:bloomers': 'female:블루머',
  'female:small breasts': 'female:빈유',
  'female:bukkake': 'female:부카케',
  'female:scat': 'female:스캇',
  'female:females only': 'female:여성만',
  'female:hairy': 'female:털많은',
  'female:harem': 'female:하렘',
  'female:blindfold': 'female:눈가리개',
  'female:inflation': 'female:팽창',
  'female:teacher': 'female:선생님',
  'female:lingerie': 'female:란제리',
  'female:demon girl': 'female:악마 소녀',
  'female:piercing': 'female:피어씽',
  'female:bbw': 'female:뚱녀',
  'female:bunny girl': 'female:토끼 소녀',
  'female:elf': 'female:엘프',
  'female:tanlines': 'female:선탠 라인',
  'female:drugs': 'female:약물',
  'female:kimono': 'female:기모노',
  'female:bestiality': 'female:수간',
  'female:fingering': 'female:성적 쾌감을 위해 손가락을 사용',
  'female:stomach deformation':
      'female:너무 큰 생식기나 물건이 들어가서 복부가 과장되게 튀어나옴',
  'female:prostitution': 'female:매춘',
  'female:school swimsuit': 'female:학교 수영복',
  'female:cunnilingus': 'female:커닐링구스',
  'female:enema': 'female:관장',
  'female:unusual pupils':
      'female:눈의 동공에 하트나 별 같은 특별한 모양이 있음',
  'female:nurse': 'female:간호사',
  'female:monster girl': 'female:여성 몬스터',
  'female:sweating': 'female:땀',
  'female:birth': 'female:출산',
  'female:sleeping': 'female:수면',
  'female:spanking': 'female:스팽킹',
  'female:rimjob': 'female:항문 빨기',
  'female:miko': 'female:무녀',
  'female:apron': 'female:에이프런',
  'female:blackmail': 'female:협박',
  'female:deepthroat': 'female:딥 펠라치오',
  'female:kissing': 'female:키스',
  'female:daughter': 'female:딸',
  'female:bodysuit': 'female:바디슈트',
  'female:big penis': 'female:큰 자지',
  'female:schoolgirl': 'female:여학생',
  'female:shibari': 'female:귀갑묶기',
  'female:thigh high boots': 'female:무릎까지 오는 부츠',
  'female:breast expansion': 'female:가슴이 커짐',
  'female:furry': 'female:수인',
  'female:gyaru': 'female:갸루',
  'female:dick growth': 'female:자지가 커짐',
  'female:slave': 'female:노예',
  'female:latex': 'female:라텍스',
  'female:leotard': 'female:레오타드',
  'female:big areolae': 'female:큰 유륜',
  'female:filming': 'female:촬영',
  'female:magical girl': 'female:마법 소녀',
  'female:cervix penetration': 'female:자궁에 직접적으로 성기를 삽입',
  'female:guro': 'female:고어',
  'female:corruption': 'female:타락',
  'female:hairy armpits': 'female:겨털',
  'female:chloroform': 'female:클로로포름',
  'female:bike shorts': 'female:스패츠',
  'female:fisting': 'female:피스팅',
  'female:urethra insertion': 'female:요도 삽입',
  'female:tiara': 'female:티아라',
  'female:fox girl': 'female:여우녀',
  'female:inverted nipples': 'female:함몰유두',
  'female:bdsm': 'female:BDSM',
  'female:group': 'female:그룹',
  'female:crossdressing': 'female:반대 성별의 옷을 입음',
  'female:shemale': 'female:쉬메일',
  'female:human pet': 'female:사람을 애완동물처럼 다룸',
  'female:incest': 'female:근친',
  'female:chikan': 'female:치한',
  'female:tomboy': 'female:외모가 남자 같은 여자',
  'female:big nipples': 'female:큰 유두',
  'female:torture': 'female:고문',
  'female:facesitting': 'female:얼굴에 앉음',
  'female:leg lock': 'female:성행위 하는 상대방을 두 다리로 끌어앉음',
  'female:gokkun': 'female:정액을 먹음',
  'female:sole dickgirl': 'female:단독 후타나리',
  'female:waitress': 'female:웨이트리스',
  'female:oppai loli': 'female:로리거유',
  'female:muscle': 'female:근육',
  'female:large insertions': 'female:큰 물건을 삽입',
  'female:tribadism': 'female:가위치기',
  'female:eggs': 'female:난생이거나 안에 알이 들어있음',
  'female:body writing': 'female:몸에 글자 쓰기',
  'female:business suit': 'female:비즈니스 정장',
  'female:eyepatch': 'female:안대',
  'female:shimapan': 'female:줄무늬 팬티',
  'female:nun': 'female:수녀',
  'female:hotpants': 'female:핫팬츠',
  'female:ryona': 'female:료나',
  'female:bride': 'female:웨딩 드레스',
  'female:drunk': 'female:술에 취함',
  'female:wings': 'female:날개',
  'female:transformation': 'female:물리적, 생물적 변화를 자세히 묘사함',
  'female:squirting': 'female:시오후키',
  'female:humiliation': 'female:굴욕',
  'female:cousin': 'female:사촌',
  'female:snuff': 'female:스너프',
  'female:double vaginal': 'female:2개의 자지가 하나의 질로 삽입됨',
  'female:tall girl': 'female:키가 큰 여성',
  'female:armpit sex': 'female:겨드랑이로 성기를 자극함',
  'female:triple penetration': 'female:3개의 구멍이 동시에 삽입당함',
  'female:dog girl': 'female:멍멍이녀',
  'female:breast feeding': 'female:가슴 빨기',
  'female:blowjob face': 'female:펠라치오로 인해 양볼이 홀쭘해지는 얼굴모양',
  'female:vore': 'female:보어물',
  'female:cheerleader': 'female:치어리더',
  'female:smell': 'female:강렬한 냄새를 방출함',
  'female:milking': 'female:모유 채취',
  'female:slime': 'female:슬라임',
  'female:gaping': 'female:섹스 후 질 또는 항문이 늘어나 있는 모습',
  'female:body modification': 'female:인체개조',
  'female:cosplaying': 'female:코스프레',
  'female:robot': 'female:로봇',
  'female:sundress': 'female:여름용 원피스',
  'female:angel': 'female:천사',
  'female:prolapse': 'female:탈장',
  'female:underwater': 'female:수중',
  'female:twins': 'female:쌍둥이',
  'female:yandere': 'female:얀데레',
  'female:amputee': 'female:사지의 일부가 손실됨',
  'female:military': 'female:밀리터리',
  'female:kunoichi': 'female:쿠노이치',
  'female:metal armor': 'female:금속 갑옷',
  'female:nose hook': 'female:코걸이',
  'female:aunt': 'female:여자 연상 친척',
  'female:giantess': 'female:거인녀',
  'female:big clit': 'female:큰 클리토리스',
  'female:possession': 'female:자신의 몸이 타인의 의지대로 움직임',
  'female:corset': 'female:코르셋',
  'female:diaper': 'female:기저귀',
  'female:chinese dress': 'female:차이나 드레스',
  'female:bisexual': 'female:양성 애자',
  'female:piss drinking': 'female:소변 마심',
  'female:public use': 'female:육변기',
  'female:machine': 'female:기계와 섹스',
  'female:oni': 'female:오니',
  'female:parasite': 'female:기생충',
  'female:cowgirl': 'female:젖소녀',
  'female:all the way through':
      'female:입이나 항문으로 물체가 삽입되어 반대편으로 나와서 몸을 관통함',
  'female:witch': 'female:마녀',
  'female:hairjob': 'female:머리카락으로 생식기를 자극',
  'female:kemonomimi': 'female:동물귀',
  'female:sumata': 'female:스마타',
  'female:blood': 'female:출혈',
  'female:wolf girl': 'female:늑대녀',
  'female:solo action': 'female:본인이 직접 성적인 행위를 하면서 즐김',
  'female:crotch tattoo': 'female:가랑이 문신',
  'female:lab coat': 'female:연구복',
  'female:tracksuit': 'female:운동복',
  'female:christmas': 'female:크리스마스',
  'female:insect': 'female:곤충',
  'female:age progression': 'female:급격히 나이를 먹음',
  'female:farting': 'female:방귀',
  'female:policewoman': 'female:여자 경찰',
  'female:tail plug': 'female:꼬리 플러그',
  'female:vomit': 'female:구토',
  'female:gothic lolita': 'female:고스로리',
  'female:mecha girl': 'female:기계 부품이 몸 밖으로 드러난 여자',
  'female:vampire': 'female:뱀파이어',
  'female:double anal': 'female:2개의 자지가 하나의 항문으로 들어감',
  'female:pasties': 'female:젖꼭지 가리개',
  'female:low lolicon': 'female:로리 내용이 있으나 비율이 적음',
  'female:gender bender': 'female:성별 전환',
  'female:randoseru': 'female:란도셀',
  'female:assjob': 'female:엉덩이 틈 사이에 자지를 비빔',
  'female:emotionless sex': 'female:무표정 섹스',
  'female:toddlercon': 'female:유아',
  'female:asphyxiation': 'female:질식',
  'female:dougi': 'female:도복',
  'female:armpit licking': 'female:겨드랑이 핥기',
  'female:stuck in wall': 'female:벽에 끼어서 움직일 수 없음',
  'female:dark nipples': 'female:흑두',
  'female:full body tattoo': 'female:전신 문신',
  'female:multiple paizuri':
      'female:하나의 남성 생식기에 여러개의 가슴이 파이즈리',
  'female:tickling': 'female:간지럼',
  'female:fairy': 'female:요정',
  'female:moral degeneration': 'female:섹스에 대한 도덕적 관념이 사라짐',
  'female:chastity belt': 'female:정조대',
  'female:big balls': 'female:큰 불알',
  'female:pillory': 'female:구속구',
  'female:eyemask': 'female:눈가리개',
  'female:huge penis': 'female:매우 큰 자지',
  'female:orgasm denial':
      'female:도구를 사용해 오르가즘에 도달하지 못하도록 함',
  'female:minigirl': 'female:소인녀',
  'female:swinging':
      'female:커플중 한 명 또는 모두가 제3자와 섹스하는 것을 허락함',
  'female:widow': 'female:과부',
  'female:snake girl': 'female:뱀녀',
  'female:ghost': 'female:유령',
  'female:wooden horse': 'female:목마',
  'female:tube': 'female:튜브',
  'female:electric shocks': 'female:전기 충격',
  'female:niece': 'female:여자조카',
  'female:masked face': 'female:가면',
  'female:selfcest': 'female:한 사람의 다른 두 버전이 서로 섹스함',
  'female:ball sucking': 'female:불알 빨기',
  'female:age regression': 'female:급격히 나이가 어려짐',
  'female:brain fuck': 'female:뇌와 관련된 섹스',
  'female:ponytail': 'female:포니테일',
  'female:long tongue': 'female:긴 혀',
  'female:autofellatio': 'female:셀프 펠라치오',
  'female:wrestling': 'female:레슬링',
  'female:foot licking': 'female:발을 핥음',
  'female:twintails': 'female:트윈테일',
  'female:speculum': 'female:질이나 항문을 벌리는 의학적 도구',
  'female:freckles': 'female:주근깨',
  'female:living clothes': 'female:살아 움직이는 옷',
  'female:bandages': 'female:붕대가 몸의 상당부분을 가림',
  'female:unbirth': 'female:질이나 항문으로 사람을 삼켜서 흡수함',
  'female:slime girl': 'female:슬라임녀',
  'female:double blowjob': 'female:2개의 자지가 하나의 입으로 들어감',
  'female:voyeurism': 'female:관음증',
  'female:pubic stubble': 'female:제모후 짧게 다시자란 음모',
  'female:ttf threesome': 'female:여트젠트젠 쓰리썸',
  'female:pantyjob': 'female:팬티잡',
  'female:human cattle': 'female:사람을 가축처럼 다룸',
  'female:mermaid': 'female:인어녀',
  'female:clit growth': 'female:클리토리스가 커짐',
  'female:whip': 'female:채찍',
  'female:condom': 'female:콘돔',
  'female:scar': 'female:흉터',
  'female:zombie': 'female:좀비',
  'female:fundoshi': 'female:훈도시',
  'female:onahole': 'female:오나홀',
  'female:clothed paizuri': 'female:옷입고 파이즈리',
  'female:multiple penises': 'female:다수의 남성기',
  'female:catfight': 'female:여자끼리 싸움',
  'female:tutor': 'female:가정교사',
  'female:tights': 'female:타이즈',
  'female:smegma': 'female:치구',
  'female:lizard girl': 'female:도마뱀 소녀',
  'female:centaur': 'female:켄타우로스',
  'female:body painting': 'female:바디페인팅',
  'female:petrification': 'female:석화',
  'female:multiple breasts': 'female:다수의 유방',
  'female:crown': 'female:왕관',
  'female:low bestiality': 'female:약간의 수간',
  'female:glory hole': 'female:글로리 홀',
  'female:gymshorts': 'female:운동바지',
  'female:dicknipples': 'female:유두자지',
  'female:harpy': 'female:하피',
  'female:skinsuit': 'female:달라붙는 옷',
  'female:sunglasses': 'female:선글라스',
  'female:smoking': 'female:흡연',
  'female:cum swap': 'female:채액 교환',
  'female:bodystocking': 'female:바디스타킹',
  'female:insect girl': 'female:곤충녀',
  'female:oil': 'female:오일',
  'female:vaginal sticker': 'female:마에바리',
  'female:frottage': 'female:프로타주',
  'female:nipple expansion': 'female:유두 팽창',
  'female:cbt': 'female:Cbt',
  'female:wormhole': 'female:웜홀',
  'female:phimosis': 'female:포경',
  'female:squid girl': 'female:오징어 소녀',
  'female:plant girl': 'female:식물 소녀',
  'female:weight gain': 'female:뚱녀',
  'female:dickgirls only': 'female:후타라니만',
  'female:mouse girl': 'female:마우스 소녀',
  'female:gigantic breasts': 'female:졸라큰 가슴',
  'female:heterochromia': 'female:얼룩증',
  'female:table masturbation': 'female:책상자위',
  'female:horse girl': 'female:말 소녀',
  'female:dark sclera': 'female:검은 흰자',
  'female:forniphilia': 'female:인간가구',
  'female:schoolboy uniform': 'female:남학생 유니폼',
  'female:syringe': 'female:주사기',
  'female:mature': 'female:성숙한',
  'female:spider girl': 'female:거미녀',
  'female:human on furry': 'female:수인에게 인간이',
  'female:snake': 'female:뱀',
  'female:navel fuck': 'female:배꼽박이',
  'female:fft threesome': 'female:여트젠트젠 쓰리썸',
  'female:alien girl': 'female:외계 소녀',
  'female:stewardess': 'female:스튜어디스',
  'female:raccoon girl': 'female:너구리 소녀',
  'female:ear fuck': 'female:귀에 삽입',
  'female:octopus': 'female:문어',
  'female:worm': 'female:벌레',
  'female:doll joints': 'female:인형관절',
  'female:sheep girl': 'female:양 소녀',
  'female:wet clothes': 'female:젖은 옷',
  'female:shared senses': 'female:감각공유',
  'female:growth': 'female:거인화',
  'female:absorption': 'female:흡수',
  'female:big vagina': 'female:허벌 보지',
  'female:infantilism': 'female:유아적인행동',
  'female:invisible': 'female:투명인간',
  'female:stretching': 'female:스트레칭',
  'female:saliva': 'female:침',
  'female:handicapped': 'female:장애인',
  'female:cum bath': 'female:정액 목욕',
  'female:unusual teeth': 'female:특이한 이빨',
  'female:coach': 'female:코치',
  'female:autopaizuri': 'female:오토파이즈리',
  'female:girls only': 'female:여자만',
  'female:necrophilia': 'female:네크로필리아',
  'female:anorexic': 'female:식용부진',
  'female:pig girl': 'female:돼지녀',
  'female:menstruation': 'female:생리혈',
  'female:anal birth': 'female:애널 출생',
  'female:tailjob': 'female:꼬리로 생식기를 자극',
  'female:cannibalism': 'female:식인',
  'female:pirate': 'female:해적',
  'female:male on futanari': 'female:남자x후타나리',
  'female:triple vaginal':
      'female:3개의 자지 또는 3개의 성기구 등이 하나의 질에 삽입됨',
  'female:eel': 'female:뱀장어 ',
  'female:granddaughter': 'female:조부모와 손녀가',
  'female:slug': 'female:복족류 연체동물',
  'female:futanari on futanari': 'female:후타나리x후타나리',
  'female:prostate massage': 'female:회음부 자극',
  'female:ass expansion': 'female:엉덩이가 커짐',
  'female:body swap': 'female:신체교환',
  'female:nipple birth': 'female:젖꼭지 출생',
  'female:pole dancing': 'female:봉춤',
  'female:race queen': 'female:레이싱 모델',
  'female:blind': 'female:눈가리개',
  'female:dragon': 'female:드래곤',
  'female:big lips': 'female:큰 입술',
  'female:frog': 'female:개구리',
  'female:eye penetration': 'female:눈에다 섹스',
  'female:kigurumi': 'female:캐릭터를 나타내는 몸 전체를 뒤덮는 코스튬',
  'female:shrinking': 'female:소인화',
  'female:nose fuck': 'female:코에다 섹스',
  'female:orc': 'female:오크',
  'female:triple anal': 'female:3개의 자지가 하나의 아날로 들어감',
  'female:multiple arms': 'female:팔이 3개 이상',
  'female:prehensile hair': 'female:머리카락을 수족처럼 다룸',
  'female:inseki': 'female:입양가족',
  'female:ponygirl': 'female:포니걸',
  'female:mother': 'female:엄마',
  'female:grandmother': 'female:할머니',
  'female:midget': 'female:난쟁이',
  'female:foot insertion': 'female:발을 삽입함',
  'female:layer cake': 'female:보지 덮밥',
  'female:cum in eye': 'female:눈에 정액 뿌리기',
  'female:bandaid': 'female:무법자',
  'female:phone sex': 'female:폰섹',
  'female:horse': 'female:말',
  'female:balls expansion': 'female:불알 확장',
  'female:spider': 'female:거미',
  'female:bee girl': 'female:꿀벌녀',
  'female:vacbed': 'female:진공침대',
  'female:balljob': 'female:불알에다가 하는 파이즈리',
  'female:kneepit sex': 'female:오금으로 자지나 유사한 물체를 자극함',
  'female:squirrel girl': 'female:다람쥐녀',
  'female:gasmask': 'female:방독면',
  'female:monoeye': 'female:외눈박이',
  'female:kindergarten uniform': 'female:유치원복',
  'female:abortion': 'female:유산',
  'female:trampling': 'female:발에 밟힘',
  'female:old lady': 'female:50세 이상 여성',
  'female:sockjob': 'female:양말플레이',
  'female:maggot': 'female:구더기',
  'female:kappa': 'female:갓파',
  'female:albino': 'female:백색증',
  'female:nazi': 'female:나치',
  'female:frog girl': 'female:개구리 소녀',
  'female:horse cock': 'female:대물',
  'female:monkey': 'female:원숭이',
  'female:robot girl': 'female:로봇 소녀',
  'female:scrotal lingerie': 'female:음낭 란제리',
  'female:first person perspective': 'female:1인칭 시점',
  'female:bald': 'female:대머리',
  'female:hijab': 'female:히잡',
  'female:dog': 'female:강아지',
  'female:legjob': 'female:다리를 사용해 자극함',
  'female:breast reduction': 'female:가슴이 작아짐',
  'female:cow': 'female:젖소',
  'female:tooth brushing': 'female:양치질',
  'female:rabbit': 'female:토끼',
  'female:burping': 'female:트림',
  'female:haigure': 'female:하이그레',
  'female:cat': 'female:고양이',
  'female:fox': 'female:여우',
  'female:mute': 'female:청각 장애인',
  'female:butler': 'female:집사',
  'female:fish': 'female:물고기',
  'female:pig': 'female:돼지',
  'female:snail girl': 'female:뱀 소녀',
  'female:goblin': 'female:고블린',
  'female:multiple nipples': 'female:3개 이상의 젖꼭지',
  'female:piercings': 'female:피어싱',
  'female:muscle growth': 'female:근육이 생기거나 커짐',
  'female:cockslapping': 'female:사람을 자지로 때림',
  'female:tiger': 'female:호랑이',
  'female:donkey': 'female:당나귀',
  'female:panda girl': 'female:판다 소녀',
  'female:mouse': 'female:쥐',
  'female:adventitious vagina': 'female:이상한 곳에 질이 있음',
  'female:reptile': 'female:파충류',
  'female:shark girl': 'female:상어 소녀',
  'female:conjoined': 'female:샴쌍둥이',
  'female:dismantling': 'female:해체',
  'female:lioness': 'female:암컷 사자',
  'female:schoolboy': 'female:남학생',
  'female:dolphin': 'female:돌고래',
  'female:wolf': 'female:늑대',
  'female:bear girl': 'female:곰 소녀',
  'female:elephant': 'female:코끼리',
  'female:animal on furry': 'female:동물x수인',
  'female:gijinka': 'female:의인화',
  'female:multiple vaginas': 'female:다수의 질',
  'female:bear': 'female:곰',
  'female:draenei': 'female:드레나이',
  'female:sheep': 'female:양',
  'female:closed eyes': 'female:감은 눈',
  'female:kangaroo': 'female:캥거루',
  'female:unicorn': 'female:유니콘',
  'female:dinosaur': 'female:공룡',
  'female:waiter': 'female:웨이터',
  'female:school uniform': 'female:교복',
  'female:blow job': 'female:펠라치오',
  'female:gymshort': 'female:짧은 운동 용 바지',
  'female:futa': 'female:후타',
  'female:clown': 'female:광대',
  'female:demon': 'female:악마',
  'female:amputation': 'female:절단 ',
  'female:spats': 'female:스패츠',
  'female:ogre': 'female:사람을 잡아먹는 거인',
  'female:dragonfly': 'female:잠자리',
  'female:stocking': 'female:스타킹',
  'female:tail': 'female:꼬리',
  'female:tall': 'female:큰 키',
  'female:tattoo': 'female:타투',
  'female:maids': 'female:메이드',
  'female:braces': 'female:치아 교정기',
  'female:crab': 'female:게',
  'female:irrumatio': 'female:이루마티오',
  'female:insects': 'female:곤충',
  'female:bandage': 'female:붕대가 몸의 상당부분을 가림',
  'female:larva': 'female:애벌레',
  'female:lamia': 'female:반인반수 괴물',
  'female:kneesock': 'female:니삭스',
  'female:worms': 'female:웜',
  'female:leeches': 'female:거머리',
  'female:animal on animal': 'female:동물x동물',
  'female:snails': 'female:뱀',
  'male:sole male': 'male:단독남성',
  'male:shota': 'male:쇼타',
  'male:yaoi': 'male:야오이',
  'male:anal': 'male:애널',
  'male:glasses': 'male:안경',
  'male:males only': 'male:남자만',
  'male:dilf': 'male:아저씨',
  'male:schoolboy uniform': 'male:남학생 교복',
  'male:crossdressing': 'male:여장',
  'male:bbm': 'male:뚱뚱한 남자',
  'male:dark skin': 'male:검은피부',
  'male:tomgirl': 'male:여자같은 남자',
  'male:muscle': 'male:근육',
  'male:gender bender': 'male:성전환',
  'male:bondage': 'male:속박',
  'male:big penis': 'male:큰 자지',
  'male:monster': 'male:목스터',
  'male:condom': 'male:콘돔',
  'male:teacher': 'male:선생님',
  'male:virginity': 'male:후장개통',
  'male:furry': 'male:수인',
  'male:blowjob': 'male:펠라치오',
  'male:stockings': 'male:스타킹',
  'male:military': 'male:밀리터리',
  'male:rape': 'male:강간',
  'male:group': 'male:그룹',
  'male:harem': 'male:하렘',
  'male:old man': 'male:노인',
  'male:pegging': 'male:페깅',
  'male:sex toys': 'male:섹스토이',
  'male:cheating': 'male:불륜',
  'male:dog': 'male:개',
  'male:prostate massage': 'male:전립선 마사지',
  'male:ahegao': 'male:아헤가오',
  'male:schoolgirl uniform': 'male:여학생 교복',
  'male:masturbation': 'male:자위',
  'male:nakadashi': 'male:애널사정',
  'male:business suit': 'male:비지니스 정장',
  'male:kimono': 'male:기모노',
  'male:collar': 'male:목걸이',
  'male:masked face': 'male:가면',
  'male:demon': 'male:악마',
  'male:blindfold': 'male:눈가리개',
  'male:snuff': 'male:스너프',
  'male:orc': 'male:오크',
  'male:catboy': 'male:캣 보이',
  'male:foot licking': 'male:발을 핥음',
  'male:exhibitionism': 'male:노출증',
  'male:handjob': 'male:핸드잡',
  'male:incest': 'male:근친',
  'male:swimsuit': 'male:수영복',
  'male:feminization': 'male:불완전 성전환',
  'male:blood': 'male:피',
  'male:bald': 'male:대머리',
  'male:rimjob': 'male:애널핥기',
  'male:urethra insertion': 'male:요도 삽입',
  'male:mind break': 'male:타락',
  'male:smegma': 'male:치구',
  'male:drugs': 'male:약물',
  'male:tentacles': 'male:촉수',
  'male:urination': 'male:방뇨',
  'male:orgasm denial': 'male:도구를 사용해 오르가즘에 도달하지 못하도록 함',
  'male:tracksuit': 'male:운동복',
  'male:sweating': 'male:땀',
  'male:maid': 'male:메이드',
  'male:brother': 'male:형제',
  'male:human on furry': 'male:수인에게 인간이',
  'male:gag': 'male:개그',
  'male:netorare': 'male:네토라레',
  'male:sunglasses': 'male:선글라스',
  'male:horse': 'male:말',
  'male:lingerie': 'male:란제리',
  'male:tall man': 'male:키큰남자',
  'male:tanlines': 'male:썬탠자국',
  'male:sleeping': 'male:수면',
  'male:frottage': 'male:프로타주',
  'male:guro': 'male:고어',
  'male:schoolboy': 'male:남학생',
  'male:pig': 'male:돼지',
  'male:mind control': 'male:마인드 컨트롤',
  'male:voyeurism': 'male:관음증',
  'male:onahole': 'male:오나홀',
  'male:coach': 'male:코치',
  'male:prostitution': 'male:매춘',
  'male:scar': 'male:흉터',
  'male:elf': 'male:엘프',
  'male:kissing': 'male:키스',
  'male:chastity belt': 'male:정조대',
  'male:blackmail': 'male:협박',
  'male:josou seme': 'male:여장이 공격',
  'male:piss drinking': 'male:소변 마심',
  'male:miniguy': 'male:작은남자',
  'male:lab coat': 'male:연구복',
  'male:unusual pupils': 'male:눈의 동공에 하트나 별 같은 특별한 모양이 있음',
  'male:bunny boy': 'male:토끼남',
  'male:x-ray': 'male:투시',
  'male:ryona': 'male:료나',
  'male:huge penis': 'male:큰 자지',
  'male:humiliation': 'male:굴욕',
  'male:footjob': 'male:풋잡',
  'male:pantyhose': 'male:팬티 스타킹',
  'male:wolf boy': 'male:늑대소년',
  'male:bdsm': 'male:BDSM',
  'male:dog boy': 'male:강아지 소년',
  'male:bikini': 'male:비키니',
  'male:eyepatch': 'male:안대',
  'male:transformation': 'male:변신',
  'male:spanking': 'male:스팽킹',
  'male:eyemask': 'male:안대',
  'male:scat': 'male:스캇',
  'male:double anal': 'male:더블애널',
  'male:guys only': 'male:남자만',
  'male:pig man': 'male:돼지남',
  'male:drunk': 'male:술에 취함',
  'male:invisible': 'male:투명',
  'male:double penetration': 'male:동시 삽입',
  'male:torture': 'male:고문',
  'male:bisexual': 'male:양성 애자',
  'male:hairy': 'male:털많은',
  'male:smell': 'male:냄세나는',
  'male:slave': 'male:노예',
  'male:tutor': 'male:가정교사',
  'male:garter belt': 'male:가터벨트',
  'male:zombie': 'male:좀비',
  'male:gyaru-oh': 'male:갸루남',
  'male:piercing': 'male:피어싱',
  'male:cosplaying': 'male:코스프레',
  'male:bestiality': 'male:수간',
  'male:first person perspective': 'male:1인칭 시점',
  'male:phimosis': 'male:포경',
  'male:fox boy': 'male:여우 소년',
  'male:school swimsuit': 'male:학교 수영복',
  'male:goblin': 'male:고블린',
  'male:vore': 'male:보어물',
  'male:bandages': 'male:붕대가 몸의 상당부분을 가림',
  'male:inflation': 'male:팽창',
  'male:age regression': 'male:급격히 나이가 어려짐',
  'male:dougi': 'male:도복',
  'male:oni': 'male:오니',
  'male:bodysuit': 'male:바디슈트',
  'male:chikan': 'male:치한',
  'male:father': 'male:아버지',
  'male:dragon': 'male:드래곤',
  'male:shibari': 'male:귀갑묶기',
  'male:possession': 'male:자신의 몸이 타인의 의지대로 움직임',
  'male:robot': 'male:로봇',
  'male:bukkake': 'male:부카케',
  'male:twins': 'male:쌍둥이',
  'male:unbirth': 'male:질이나 항문으로 사람을 삼켜서 흡수함',
  'male:filming': 'male:촬영',
  'male:minotaur': 'male:미니어쳐',
  'male:policeman': 'male:경찰',
  'male:enema': 'male:관장',
  'male:low shotacon': 'male:쇼타 내용이 있으나 비율이 적음',
  'male:armpit licking': 'male:겨드랑이 핥기',
  'male:butler': 'male:집사',
  'male:apron': 'male:앞치마',
  'male:bloomers': 'male:블루머',
  'male:diaper': 'male:기저귀',
  'male:dick growth': 'male:자지가 커짐',
  'male:fundoshi': 'male:훈도시',
  'male:bike shorts': 'male:스패츠',
  'male:amputee': 'male:사지의 일부가 손실됨',
  'male:giant': 'male:거인',
  'male:lizard guy': 'male:도마뱀 남',
  'male:layer cake': 'male:보지 덮밥',
  'male:futanari on male': 'male:후타나리에게 박힘',
  'male:full body tattoo': 'male:전신 문신',
  'male:stomach deformation':
      'male:너무 큰 생식기나 물건이 들어가서 복부가 과장되게 튀어나옴',
  'male:gokkun': 'male:정액',
  'male:ghost': 'male:귀신',
  'male:alien': 'male:외계인',
  'male:multiple penises': 'male:다수의 남성기',
  'male:fisting': 'male:피스팅',
  'male:lactation': 'male:수유',
  'male:nurse': 'male:간호사',
  'male:wolf': 'male:늑대',
  'male:corruption': 'male:타락',
  'male:horse boy': 'male:말 소년',
  'male:asphyxiation': 'male:질식',
  'male:freckles': 'male:주근깨',
  'male:insect': 'male:곤충',
  'male:selfcest': 'male:한 사람의 다른 두 버전이 서로 섹스함',
  'male:waiter': 'male:웨이터',
  'male:big balls': 'male:큰 불알',
  'male:ninja': 'male:닌자',
  'male:shrinking': 'male:소인화',
  'male:latex': 'male:라텍스',
  'male:leotard': 'male:레오타드',
  'male:vampire': 'male:뱀파이어',
  'male:facesitting': 'male:얼굴에 앉음',
  'male:human pet': 'male:human 사람을 애완동물처럼 다룸',
  'male:deepthroat': 'male:딥 펠라치오',
  'male:tiara': 'male:왕관',
  'male:metal armor': 'male:중세 시대의 금속 갑옷',
  'male:slime': 'male:슬라임',
  'male:big ass': 'male:큰 엉덩이',
  'male:kemonomimi': 'male:동물귀',
  'male:unusual teeth': 'male:특이한 이빨',
  'male:sundress': 'male:여름용 원피스',
  'male:pregnant': 'male:임신',
  'male:gymshorts': 'male:운동바지',
  'male:solo action': 'male:본인이 직접 성적인 행위를 하면서 즐김',
  'male:shimapan': 'male:줄무늬 팬티',
  'male:long tongue': 'male:긴 혀',
  'male:christmas': 'male:크리스마스',
  'male:yandere': 'male:얀데레',
  'male:whip': 'male:채찍',
  'male:chloroform': 'male:클로로포름',
  'male:cheerleader': 'male:치어리더',
  'male:bear boy': 'male:곰 소년',
  'male:bull': 'male:황소',
  'male:glory hole': 'male:글로리 홀',
  'male:chinese dress': 'male:차이나 드레스',
  'male:body swap': 'male:신체교환',
  'male:angel': 'male:천사',
  'male:inseki': 'male:입양가족',
  'male:breast expansion': 'male:가슴 팽창',
  'male:toddlercon': 'male:유아',
  'male:bride': 'male:웨딩 드레스',
  'male:monkey': 'male:원숭이',
  'male:thigh high boots': 'male:무릎까지 오는 부츠',
  'male:priest': 'male:사제',
  'male:infantilism': 'male:유아적인행동',
  'male:autofellatio': 'male:셀프 펠라치오',
  'male:gaping': 'male:섹스 후 질 또는 항문이 늘어나 있는 모습',
  'male:impregnation': 'male:수정',
};

module.exports = kor_tag;