//===----------------------------------------------------------------------===//
//
//                       Violet Tag Info Program
//
//===----------------------------------------------------------------------===//
//
//  Copyright (C) 2021. violet-team. All Rights Reserved.
//
//===----------------------------------------------------------------------===//

const kor_series = {
  'princess connect': '프린세스 커넥트 시리즈',
  'touhou project': '동방 프로젝트',
  'kantai collection': '함대 컬렉션',
  'the idolmaster': '아이돌 마스터',
  'fate grand order': '페이트 그랜드 오더',
  'neon genesis evangelion': '신세기 에반게리온',
  'sailor moon': '세일러문',
  'mahou shoujo lyrical nanoha': '마법소녀 리리컬 나노하',
  'pokemon': '포켓몬',
  'to love-ru': 'To LOVE 트러블',
  'love live': '러브라이브',
  'naruto': '나루토',
  'granblue fantasy': '그랑블루 판타지',
  'one piece': '원피스',
  'fate stay night': '페이트 스테이 나이트',
  'street fighter': '스트리트 파이터',
  'k-on': '케이온',
  'king of fighters': '더 킹 오브 파이터즈',
  'sword art online': '소드 아트 온라인',
  'dead or alive': 'Dead or Alive',
  'puella magi madoka magica': '마법소녀 마도카 마기카',
  'ore no imouto ga konna ni kawaii wake ga nai':
      '내 여동생이 이렇게 귀여울 리가 없어',
  'girls und panzer': '걸즈 & 판처',
  'code geass': '코드 기어스',
  'the melancholy of haruhi suzumiya': '스즈미야 하루히의 우울',
  'bakemonogatari': '바케모노가타리',
  'free': '프리!',
  'final fantasy vii': '파이널 판타지 7',
  'bleach': '블리치',
  'toheart2': '투 하트2',
  'boku wa tomodachi ga sukunai': '나는 친구가 적다',
  'dragon quest iii': '드래곤 퀘스트 3',
  'ragnarok online': '라그나로크 온라인',
  'queens blade': '퀸즈 블레이드',
  'toaru kagaku no railgun': '어떤 과학의 초전자포',
  'vocaloid': '보컬로이드',
  'ah my goddess': '오! 나의 여신님',
  'cardcaptor sakura': '카드캡터 채리',
  'shingeki no kyojin': '진격의 거인',
  'monster hunter': '몬스터 헌터',
  'infinite stratos': '인피니트 스트라토스',
  'dragon ball z': '드래곤볼 Z',
  'smile precure': '스마일 프리큐어!',
  'darkstalkers': 'Darkstalkers',
  'azur lane': '벽람항로',
  'gochuumon wa usagi desu ka': '주문은 토끼입니까?',
  'toaru majutsu no index': '어떤 마술의 금서목록',
  'samurai spirits': '사무라이 스피리츠',
  'mahou sensei negima': '마법선생 네기마!',
  'gundam seed destiny': '기동전사 건담 SEED DESTINY',
  'persona 4': '페르소나 4',
  'amagami': '아마가미',
  'zero no tsukaima': '제로의 사역마',
  'saki': '사키',
  'super robot wars': '슈퍼 로봇 대전',
  'dragon quest v': '드래곤 퀘스트 V',
  'strike witches': '스트라이크 위치즈',
  'touken ranbu': '도검난무',
  'kuroko no basuke': '쿠로코의 농구',
  'lucky star': '러키☆스타',
  'to heart': '투 하트',
  'ranma 12': '란마 12',
  'love plus': '러브플러스',
  'kanon': '카논',
  'ojamajo doremi': '꼬마마법사 레미',
  'dragon quest iv': '드래곤 퀘스트 IV',
  'kono subarashii sekai ni syukufuku o': '이 멋진 세계에 축복을!',
  'sakura taisen': '사쿠라 대전',
  'league of legends': '리그 오브 레전드',
  'danganronpa': '단간론파',
  'my hero academia': '나의 히어로 아카데미아',
  'love hina': '러브히나',
  'hayate no gotoku': '하야테처럼!',
  'tengen toppa gurren lagann': '천원돌파 그렌라간',
  'love live sunshine': '러브라이브 션샤인',
  'pretty cure': '프리큐어',
  'martian successor nadesico': '기동전함 나데시코',
  'yu-gi-oh': '유희왕',
  'dragon ball': '드래곤볼',
  'dragon quest': '드래곤 퀘스트',
  'tenchi muyo': '천지무용!',
  'chuunibyou demo koi ga shitai': '중2병이라도 사랑이 하고 싶어!',
  'guilty gear': '길티 기어',
  'rozen maiden': '로젠 메이든',
  'amagi brilliant park': '아마기 브릴리언트 파크',
  'gundam build fighters': '건담 빌드 파이터즈',
  'gundam seed': '기동전사 건담',
  'fullmetal alchemist': '강철의 연금술사',
  'fate kaleid liner prisma illya': 'Fate/kaleid liner 프리즈마☆이리야',
  'haikyuu': '하이큐!!',
  'gundam 00': '기동전사 건담 더블 오',
  'soulcalibur': '소울칼리버',
  'sister princess': '시스터 프린세스',
  'dungeon ni deai o motomeru no wa machigatteiru darou ka':
      '던전에서 만남을 추구하면 안 되는 걸까',
  'ichigo 100': '딸기 100%',
  'kyoukai senjou no horizon': '경계선상의 호라이즌',
  'heartcatch precure': '하트캐치 프리큐어!',
  'macross frontier': '마크로스 프론티어',
  'suite precure': '스위트 프리큐어♪',
  'gundam build fighters try': '건담 빌드 파이터즈 트라이',
  'dokidoki precure': '두근두근! 프리큐어',
  're zero kara hajimeru isekai seikatsu': 'Re:제로부터 시작하는 이세계 생활',
  'fate zero': '페이트 제로',
  'yahari ore no seishun love come wa machigatteiru':
      '역시 내 청춘 러브코메디는 잘못됐다.',
  'fate hollow ataraxia': 'Fate/hollow ataraxia',
  'shokugeki no soma': '식극의 소마',
  'tsukihime': '월희',
  'senran kagura': '섬란 카구라',
  'fairy tail': '페어리 테일',
  'final fantasy xi': '파이널 판타지 11',
  'axis powers hetalia': '헤타리아 Axis Powers',
  'urusei yatsura': '시끌별 녀석들',
  'working': 'WORKING!!',
  'detective conan': '명탐정 코난',
  'resident evil': '레지던트 이블',
  'nisekoi': '니세코이',
  'dog days': '도그 데이즈',
  'seiken densetsu 3': '성검전설 3',
  'higurashi no naku koro ni': '쓰르라미 울 적에',
  'blazblue': '블레이블루',
  'shinrabansho': '신라만상',
  'persona 3': '페르소나 3',
  'steinsgate': '슈타인즈 게이트',
  'ano hi mita hana no namae wo bokutachi wa mada shiranai':
      '그날 본 꽃의 이름을 우리는 아직 모른다',
  'onegai teacher': '플리즈 티처',
  'yotsubato': '요츠바랑!',
  'kemono friends': '케모노 프렌즈',
  'eromanga sensei': '에로망가 선생',
  'azumanga daioh': '아즈망가 대왕',
  'dream c club': 'Dream Club',
  'gintama': '은혼',
  'school rumble': '스쿨럼블',
  'inazuma eleven': '이나즈마 일레븐',
  'dynasty warriors': '진·삼국무쌍',
  'mitsudomoe': '쓰리몬',
  'keroro gunsou': '개구리 중사 케로로',
  'hyperdimension neptunia': '초차원게임 넵튠',
  'go princess precure': 'Go! 프린세스 프리큐어',
  'pripara': '프리파라',
  'fresh precure': '프레시 프리큐어!',
  'toradora': '토라도라!',
  'highschool of the dead': '학원묵시록',
  'space battleship yamato': '우주전함 야마토',
  'gundam': '건담',
  'tokimeki memorial': '두근두근 메모리얼',
  'clannad': '클라나드',
  'yowamushi pedal': '겁쟁이 페달',
  'my little pony friendship is magic': '마이 리틀 포니: 우정은 마법',
  'final fantasy': '파이널 판타지',
  'dagashi kashi': '다가시카시',
  'aikatsu': '아이 엠 스타!',
  'maria-sama ga miteru': '마리아님이 보고계셔',
  'ikkitousen': '일기당천',
  'tiger and bunny': 'TIGER & BUNNY',
  'sennen sensou aigis': '천년전쟁 아이기스',
  'baka to test to shoukanjuu': '바보와 시험과 소환수',
  'hyouka': '빙과',
  'tekken': '철권',
  'cardfight vanguard': '카드파이트!! 뱅가드',
  'slayers': '슬레이어즈',
  'super sonico': '슈퍼 소니코',
  'etrian odyssey': 'Etrian Odyssey',
  'the legend of zelda': '젤다의 전설',
  'tales of the abyss': '테일즈 오브 어비스',
  'kannagi': '칸나기',
  'dragon quest viii': '드래곤 퀘스트 8',
  'kill la kill': '킬라킬',
  'magic knight rayearth': '마법기사 레이어스',
  'persona 5': '페르소나 5',
  'fire emblem': '파이어 엠블렘',
  'digimon': '디지몬',
  'galaxy angel': '갤럭시 엔젤',
  'ao no exorcist': '청의 엑소시스트',
  'yes precure 5': 'Yes! 프리큐어5',
  'spice and wolf': '늑대와 향신료',
  'one punch man': '원펀맨',
  'saenai heroine no sodatekata': '시원찮은 그녀를 위한 육성방법',
  'yu-gi-oh zexal': '유희왕 ZEXAL',
  'dirty pair': '더티페어',
  'mai-hime': '마이히메',
  'magi the labyrinth of magic': '마기',
  'genshiken': '현시연',
  'fire emblem if': '파이어 엠블렘',
  'accel world': '액셀 월드',
  'happinesscharge precure': '해피니스 차지 프리큐어!',
  'god eater': '갓 이터',
  'yu-gi-oh arc-v': '유희왕 ARC-V',
  'black lagoon': '블랙 라군',
  'disgaea': '마계전기 디스가이아',
  'jojos bizarre adventure': '죠죠의 기묘한 모험',
  'chobits': '쵸비츠',
  'fushigi no umi no nadia': '신비한 바다의 나디아',
  'fushigiboshi no futagohime': '신비한 별의 쌍둥이 공주',
  'uta no prince-sama': '노래의☆왕자님♪',
  'inuyasha': '이누야샤',
  'kimikiss': '키미키스',
  'angel beats': '엔젤 비트',
  'comic party': '코믹 파티',
  'katekyo hitman reborn': '가정교사 히트맨 REBORN!',
  'highschool dxd': '하이스쿨 D×D',
  'digimon adventure': '디지몬 어드벤처',
  'quiz magic academy': '퀴즈 매직 아카데미',
  'yuruyuri': '유루유리',
  'sora no otoshimono': '하늘의 유실물',
  'kizuato': '키즈아토',
  'durarara': '듀라라라!!',
  'ookiku furikabutte': '크게 휘두르며',
  'dragon quest xi': '드래곤 퀘스트 11',
  'kodomo no jikan': '아이들의 시간',
  'sekirei': '세키레이',
  'hunter x hunter': '헌터 × 헌터',
  'xenosaga': '제노사가',
  'bakuman': '바쿠만',
  'panty and stocking with garterbelt': '팬티 & 스타킹 with 가터벨트',
  'final fantasy xii': '파이널 판타지 12',
  'arcana heart': '아르카나 하트',
  'final fantasy tactics': 'Final Fantasy Tactics',
  'valkyria chronicles': '전장의 발큐리아',
  'tales of vesperia': '테일즈 오브 베스페리아',
  'ensemble stars': '앙상블 스타즈!',
  'oshiete galko-chan': '가르쳐줘! 갸루코쨩',
  'mahouka koukou no rettousei': '마법과고교의 열등생',
  'fatal fury': '아랑전설',
  'koihime musou': '연희무쌍',
  'minami-ke': '미나미가',
  'gunparade march': '건퍼레이드 오케스트라',
  'doraemon': '도라에몽',
  'shakugan no shana': '작안의 샤나',
  'alice in wonderland': '이상한 나라의 앨리스',
  'date a live': '데이트 어 라이브',
  'megaman': '록맨',
  'super mario brothers': '슈퍼 마리오브라더스',
  'maison ikkoku': '메종일각',
  'record of lodoss war': '로도스도 전기',
  'summer wars': '썸머 워즈',
  'ano natsu de matteru': '그 여름에서 기다릴게',
  'fire emblem awakening': '파이어 엠블렘 어웨이킹',
  'saint seiya': '세인트 세이야',
  'final fantasy x': '파이널 판타지 10',
  'twin angels': '음수성전',
  'pretty sammy': '마법 소녀 프리티 사미',
  'uchuu no stellvia': '우주의 스텔비아',
  'mobile suit gundam tekketsu no orphans': '기동전사 건담 철혈의 오펀스',
  'tokyo ghoul': '도쿄 구울',
  'the world god only knows': '신만이 아는 세계',
  'mobile suit gundam': '기동전사 건담',
  'senki zesshou symphogear': '전희절창 심포기어',
  'hentai ouji to warawanai neko': '변태왕자와 웃지 않는 고양이',
  'puzzle and dragons': '퍼즐앤드래곤',
  'final fantasy x-2': '파이널 판타지 X-2',
  'ro-kyu-bu': '로큐브!',
  'mai-otome': '마이 오토메',
  'eureka 7': '유레카 7',
  'kochikame': '여기는 잘나가는 파출소',
  'hataraku maou-sama': '알바 뛰는 마왕님!',
  'hikaru no go': '히카루의 바둑',
  'yuri on ice': '유리!!! on ICE',
  'final fight': '파이널 파이트',
  'historys strongest disciple kenichi': '사상최강의 제자 켄이치',
  'kobayashi-san-chi no maid dragon': '코바야시네 메이드래곤',
  'medaka box': '메다카 박스',
  'gegege no kitarou': '게게게의 기타로',
  'maho girls precure': '마법사 프리큐어!',
  'kirakira precure a la mode': '키라키라☆프리큐어 아라모드',
  'chousoku henkei gyrozetter': '초속변형 자이로제타',
  'sengoku basara': '전국 바사라',
  'zettai junpaku mahou shoujo': '절대순백 ♡ 마법소녀',
  'sentimental graffiti': '센티멘탈 그래피티',
  'metroid': '메트로이드',
  'cutey honey': '큐티 하니',
  'shinryaku ika musume': '침략! 오징어 소녀',
  'ichigo mashimaro': '딸기 마시마로',
  'final fantasy v': '파이널 판타지 10',
  'di gi charat': '디지캐럿',
  'gaogaigar': '용자왕 가오가이가',
  'full metal panic': '풀 메탈 패닉!',
  'final fantasy xiii': '파이널 판타지 13',
  'shirobako': '시로바코',
  'beatmania': '비트매니아',
  'sayonara zetsubou sensei': '안녕, 절망선생',
  'hanasaku iroha': '꽃이 피는 첫걸음',
  'ace attorney': '역전재판',
  'rance': '란스',
  'maoyuu maou yuusha': '마오유우 마왕용사',
  'lotte no omocha': '롯테의 장난감!',
  'aquarion evol': '아쿠에리온 EVOL',
  'final fantasy vi': '파이널 판타지 11',
  'nier automata': '니어:오토마타',
  'haiyore nyaruko-san': '기어와라! 냐루코 양',
  'tera': '테라',
  'kekkai sensen': '혈계전선',
  'gundam zz': '기동전사 건담 ZZ',
  'new game': 'NEW GAME!',
  'witchblade': '위치블레이드',
  'harry potter': '해리 포터',
  'battle athletes': '파이팅! 대운동회',
  'daiya no ace': '다이아몬드 A',
  'overwatch': '오버워치',
  'final fantasy iv': '파이널 판타지 4',
  'inu x boku ss': '이누×보쿠SS',
  'zettai karen children': '절대 가련 칠드런',
  'dragon quest dai no daibouken': '타이의 대모험',
  'tantei opera milky holmes': '탐정 오페라 밀키홈즈',
  'd.gray-man': '디 그레이맨',
  'fun fun pharmacy': '신비한 마법 판판 파마시 ',
  'death note': '데스노트',
  'rurouni kenshin': '바람의 검심',
  'nanatsu no taizai': '일곱 개의 대죄',
  'youre under arrest': '체포하라',
  'bayonetta': '베요네타',
  'undertale': '언더테일',
  'suisei no gargantia': '취성의 가르간티아',
  'sonic the hedgehog': '소닉 더 헤지호그',
  'air': '에어',
  'non non biyori': '논논비요리',
  'prison school': '감옥학원',
  'onegai my melody': '부탁해! 마이멜로디',
  'hell teacher nube': '지옥선생 누베',
  'taimanin yukikaze': '대마인 유키카제',
  'ultraman': '울트라맨',
  'rumble roses': '럼블로즈',
  'soul eater': '소울 이터',
  'splatoon': '스플래툰',
  'final fantasy ix': '파이널 판타지 9',
  'bakusou kyoudai lets and go': '우리는 챔피언',
  'little busters': '리틀 버스터즈',
  'g gundam': '기동무투전 G 건담',
  'girls frontline': '소녀전선',
  'da capo': '다카포',
  'boruto': '보루토',
  'akazukin cha cha': '빨간 망토 차차',
  'ghost in the shell': '공각기동대',
  'revolutionary girl utena': '소녀혁명 우테나',
  'hibike euphonium': '울려라! 유포니엄',
  'monster girl quest': '몬무스 퀘스트',
  'fate extra': 'Fate/EXTRA',
  'osomatsu-san': '오소마츠상',
  'tamako market': '타마코 마켓',
  'its not my fault that im not popular':
      '내가 인기 없는 건 아무리 생각해도 너희들 탓이야!',
  'busou renkin': '무장연금',
  'battle spirits': '배틀 스피리츠',
  'xenogears': '제노기어스',
  'umineko no naku koro ni': '괭이갈매기 울 적에',
  'vividred operation': '비비드레드 오퍼레이션',
  'rosario vampire': '로자리오와 뱀파이어',
  'pani poni dash': '파니포니 대쉬',
  'mabinogi': '마비노기',
  'turn a gundam': '턴에이 건담',
  'puyo puyo': '뿌요뿌요',
  'koutetsujou no kabaneri': '갑철성의 카바네리',
  'onegai twins': '오네가이 트윈즈',
  'zoids genesis': '조이드 제네시스',
  'denpa onna to seishun otoko': '전파녀와 청춘남',
  'ghost sweeper mikami': '고스트 스위퍼 미카미',
  'hoozuki no reitetsu': '호오즈키의 냉철',
  'tokyo mew mew': '베리베리 뮤우뮤우',
  'tales of symphonia': '테일즈 오브 심포니아',
  'bamboo blade': '뱀부 블레이드',
  'pangya': '팡야',
  'kimi no na wa.': '너의 이름은.',
  'getsuyoubi no tawawa': '월요일의 타와와',
  'he is my master': '나의 주인님',
  'powerpuff girls z': '파워퍼프걸Z',
  'hidamari sketch': '히다마리 스케치',
  'voiceroid': '보이스로이드',
  'mahou tsukai no yoru': '마법사의 밤',
  'pia carrot': '웰컴 투 피아 캐럿',
  'final fantasy viii': '파이널 판타지 8',
  'dragon quest ii': '드레곤 퀘스트 2',
  'onmyou taisenki': '음양대전기',
  'elsword': '엘소드',
  'creamy mami': '천사소녀 새롬이',
  'read or die': 'R.O.D',
  'zootopia': '주토피아',
  'world trigger': '월드 트리거',
  'sekai seifuku bouryaku no zvezda': '세계정복 ~모략의 즈베즈다~',
  'digimon tamers': '디지몬 테이머즈',
  'kimagure orange road': '변덕스러운 오렌지로드',
  'yu-gi-oh 5ds': '유희왕 5D',
  'himouto umaru-chan': '건어물 여동생! 우마루짱',
  'tales of graces': '테일즈 오브 그레이세스',
  'dragon ball super': '드래곤볼 슈퍼',
  'aldnoah.zero': '알드노아. 제로',
  'eyeshield 21': '아이실드 21',
  'ansatsu kyoushitsu': '암살교실',
  'dennou coil': '전뇌 코일',
  'darling in the franxx': '달링 인 더 프랑키스',
  'da capo ii': '다카포 2',
  'shaman king': '샤먼킹',
  'berserk': '베르세르크',
  'tokyo 7th sisters': 'Tokyo 7th 시스터즈',
  'witch craft works': '위치 크래프트 워크스',
  'lupin iii': '루팡 3세',
  'youkai watch': '요괴워치',
  'saber marionette': '세이버 마리오넷',
  'nichijou': '일상',
  'myriad colors phantom world': '무채한의 팬텀 월드',
  'little red riding hood': '빨간 두건',
  'arpeggio of blue steel': '푸른 강철의 아르페지오',
  'shin megami tensei': '진 여신전생',
  'zeta gundam': 'Z 건담',
  'ore twintail ni narimasu.': '저, 트윈 테일이 됩니다',
  'dungeon fighter online': '던전앤파이터',
  'cosmic baton girl comet-san': 'Cosmic Baton Girl 코메트상☆',
  'overlord': '오버로드',
  'gate - jietai kano chi nite kaku tatakaeri':
      '게이트 - 자위대. 그의 땅에서, 이처럼 싸우며',
  'black butler': '흑집사',
  'kiddy grade': '키디 그레이드',
  'gad guard': '가드 가드',
  'prince of tennis': '테니스의 왕자',
  'zoids': '조이드',
  'muv-luv alternative total eclipse': '마브러브 얼터너티브 토탈 이클립스 ',
  'kiniro mosaic': '금빛 모자이크',
  'nurarihyon no mago': '누라리횬의 손자',
  'galaxy express 999': '은하철도 999',
  'yu-gi-oh gx': '유희왕 GX',
  'dramatical murder': '드라마티컬 머더',
  'angelic layer': '기동천사 엔젤릭 레이어',
  'oda nobuna no yabou': '오다 노부나의 야망',
  'expelled from paradise': '낙원추방',
  'samurai warriors': '전국무쌍',
  'mirai nikki': '미래일기',
  'no game no life': '노 게임·노 라이프',
  '7th dragon': '세븐스 드래곤',
  'mayo chiki': '마요치키!',
  'kimi ga nozomu eien': '그대가 바라는 영원',
  'made in abyss': '메이드 인 어비스',
  'hand maid may': '핸드 메이드 메이',
  'princess lover': '프린세스 러버',
  'princess crown': '프린세스 크라운',
  'princess resurrection': '괴물왕녀',
  'gabriel dropout': '가브릴 드롭아웃',
  'beat blades haruka': '초앙전인 하루카',
  'papa no iu koto wo kikinasai': '아빠 말 좀 들어라!',
  'final fantasy xv': '파이널 판타지 15',
  'maria holic': '마리아†홀릭',
  'ashita no nadja': '내일의 나쟈',
  'macross 7': '마크로스7',
  'gakkou no kaidan': '학교괴담',
  'fate apocrypha': 'Fate/Apocrypha',
  'inazuma eleven go': '이나즈마 일레븐 GO',
  'tokyo afterschool summoners': '도쿄 방과후 서모너즈',
  'hellsing': '헬싱',
  'anyamaru tantei kiruminzoo': '쥬로링 동물탐정',
  'fantasy earth zero': '판타지 어스: 제로',
  'giant robo': '자이언트 로보',
  'virtua fighter': '버추어 파이터',
  'monster musume no iru nichijou': '몬스터 아가씨가 있는 일상',
  'cats eye': '캐츠 아이',
  'another': '어나더',
  'ookami-san to shichinin no nakama-tachi': '오오카미 씨와 7명의 동료들',
  'moyashimon': '모야시몬',
  'danball senki': '골판지전기',
  'mahoromatic': '마호로매틱',
  'kino no tabi': '키노의 여행',
  'gundam unicorn': '기동전사 건담 UC',
  'kanokon': '카노콘',
  'log horizon': '로그 호라이즌',
  'mahou no juujin foxy rena': '마법의 십자가 · 호쿠 레이나',
  'gantz': '간츠',
  'tower of druaga': '드루아가의 탑',
  'variable geo': '베리어블 지오',
  'cowboy bebop': '카우보이 비밥',
  'seraph of the end': '종말의 세라프',
  'phantasy star online': '판타지 스타 온라인',
  'white album': '화이트 앨범',
  'x-men': '엑스맨',
  'maji de watashi ni koi shinasai': '진심으로 날 사랑해라!!',
  'occult academy': '세기말 오컬트 학원',
  'seto no hanayome': '세토의 신부',
  'jormungand': '요르문간드',
  'final fantasy xiv': '파이널 판타지 14',
  'hitsugi no chaika': '관희 챠이카',
  'world masterpiece theater': '세계명작극장',
  'gj-bu': 'GJ부',
  'sono hanabira ni kuchizuke o': '그 꽃잎에 입맞춤을',
  'inyouchuu': '음요충',
  'kindaichi shounen no jikenbo': '소년탐정 김전일',
  'gunslinger girl': '건슬링거 걸',
  'kampfer': '캠퍼',
  'black bullet': '블랙 불릿',
  'nausicaa of the valley of the wind': '바람계곡의 나우시카',
  'mamotte shugogetten': '수호월천',
  'kaitou tenshi twin angel': '쾌도천사 트윈 엔젤',
  'utawarerumono itsuwari no kamen': '칭송을 받는 자: 거짓의 가면',
  'ai yori aoshi': '쪽빛보다 푸르게',
  'city hunter': '시티헌터',
  'devil may cry': '데빌 메이 크라이',
  'digimon frontier': '디지몬 프론티어',
  'medabots': '메다로트',
  'tales of zestiria': '테일즈 오브 제스티리아',
  'yuyushiki': '유유시키',
  'tobe isami': '날아라 이사미',
  'sora wo kakeru shoujo': '우주를 달리는 소녀',
  'ar tonelico': '아르 토네리코',
  'super doll licca-chan': '인형공주 리카',
  'kid icarus': '키드 이카루스',
  'blend s': '블렌드·S',
  'pretty rhythm': '프리티 리듬',
  'victory gundam': '기동전사 V 건담',
  'gear fighter dendoh': '기어전사 덴도우',
  'valkyrie profile': '발키리 프로파일',
  'minky momo': '요술공주 밍키',
  'little witch academia': '리틀 위치 아카데미아',
  'star gladiator': '스타 글래디에이터',
  'big hero 6': '빅 히어로',
  'final fantasy unlimited': '파이널 판타지 언리미티드',
  'phantasy star': '판타지 스타',
  'psycho-pass': '사이코 패스',
  'el hazard': '엘하자드',
  'wedding peach': '웨딩피치',
  'lord of lords ryu knight': '패왕대계 류나이트',
  'ouran high school host club': '오란고교 호스트부',
  'walkure romanze': '왈큐레 로만체',
  'solatorobo': '소라토로보',
  'dragon ball gt': '드래곤볼 GT',
  'valkyrie no bouken': '왈큐레의 모험',
  'claymore': '클레이모어',
  'the vision of escaflowne': '천공의 에스카플로네',
  'saint tail': '천사소녀 네티',
  'sonic soldier borgman': '초음전사 보그맨',
  'fruits basket': '후르츠 바스켓',
  'cream lemon': '크림 레몬',
  'gunbuster': '건버스터',
  'hacka doll': '해커돌',
  'dragon quest vi': '드래곤 퀘스트 6',
  'wizard of oz': '오즈의 마법사',
  'hatsukoi limited': '첫사랑 한정',
  'moetan': '모에땅',
  'night shift nurses': '야근병동',
  'yuru camp': '유루캠프△',
  'noir': '느와르',
  'gatchaman crowds': '갓챠맨 크라우즈',
  'mahoujin guru guru': '마법진 구루구루',
  'akihabara dennou gumi': '아키하바라 전뇌조',
  'maken-ki': '마켄키',
  'ben-to': '도시락 전쟁',
  'majin tantei nougami neuro': '마인탐정 네우로',
  'tales of': '테일즈 시리즈',
  'outbreak company': '아웃브레이크 컴퍼니',
  'atelier totori': '토토리의 아틀리에',
  'megaman battle network': '메가맨 배틀 네트워크',
  'gundam age': '기동전사건담 에이지',
  'popn music': '팝픈뮤직',
  'dragon quest x': '드래곤 퀘스트 10',
  'girl friend beta': '걸 프렌드 (베타)',
  'yatterman': '이겨라 승리호',
  'kaleido star': '카레이도 스타',
  'skies of arcadia': '스카이즈 오브 알카디아',
  'black rock shooter': '블랙 락 슈터',
  'yakitate japan': '따끈따끈 베이커리',
  'nagi no asukara': '잔잔한 내일로부터 ',
  'freezing': '프리징',
  'gakkou gurashi': '학교생활!',
  'sengoku otome': '전국 소녀',
  'shugo chara': '캐릭캐릭 체인지',
  'rakudai kishi no cavalry': '낙제기사의 영웅담',
  'nyan koi': '냥코이!',
  'show by rock': '쇼 바이 락!!',
  'renkin san-kyuu magical pokaan': '연금3급 매지컬 포카앙',
  'kamen rider': '가면 라이더',
  'nurse witch komugi': '너스위치 코무기짱',
  'strike the blood': '스트라이크 더 블러드',
  'batman': '배트맨',
  'asobi ni iku yo': '놀러 갈게!',
  'kangoku senkan': '감옥전함',
  'warriors orochi': '무쌍 오로치',
  'ryuuou no oshigoto': '용왕이 하는 일!',
  'odin sphere': '오딘 스피어',
  'busou shinki': '무장신희',
  'agent aika': '에이젼트 아이카',
  'yoru no yatterman': '밤의 얏타맨',
  'kuroinu kedakaki seijo wa hakudaku ni somaru':
      '흑수(크로이누) ~고상한 성녀는 백탁에 물들다~',
  'sakurasou no pet na kanojo': '사쿠라장의 애완그녀',
  'athena': '아테나',
  'star driver': '스타 드라이버',
  'toriko': '토리코',
  'kaichou wa maid-sama': '회장님은 메이드 사마',
  'dangaioh': '당가이오',
};