// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-a121DD9_cKyFbygQ793h5dZIQHP_RTE',
    appId: '1:774645671791:web:267e489062ff083a772a9a',
    messagingSenderId: '774645671791',
    projectId: 'real-violet-app',
    authDomain: 'real-violet-app.firebaseapp.com',
    databaseURL: 'https://real-violet-app.firebaseio.com',
    storageBucket: 'real-violet-app.appspot.com',
    measurementId: 'G-XWHN27W57L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOMT1mm45jAC8L7uTkmsH1cTcyK77q_5k',
    appId: '1:774645671791:android:303c295f5a687ceb772a9a',
    messagingSenderId: '774645671791',
    projectId: 'real-violet-app',
    databaseURL: 'https://real-violet-app.firebaseio.com',
    storageBucket: 'real-violet-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBLzu9vcpmIogaaXtL7naRLSN_XGpjgZE',
    appId: '1:774645671791:ios:b4d4f5984ef11c58772a9a',
    messagingSenderId: '774645671791',
    projectId: 'real-violet-app',
    databaseURL: 'https://real-violet-app.firebaseio.com',
    storageBucket: 'real-violet-app.appspot.com',
    iosClientId:
        '774645671791-kpjcq7n5g2ap84nco7j2iab603tkrf0m.apps.googleusercontent.com',
    iosBundleId: 'xyz.project.violet',
  );
}
