// This source code is a part of Project Violet.
// Copyright (C) 2020. violet-team. Licensed under the MIT License.

class Artists {
  static Map<Map<String, dynamic>, dynamic> collection = {
    //
    //  Masculine Artists
    //
    {'default': 'COMIC快楽天', 'ko': '코믹 쾌락천', 'ja': 'COMIC快楽天'}: [
      'homunculus',
      'hamao',
      'tosh',
      'napata',
      'hisasi',
      //
      'konchiki',
      'redrop',
      'okara',
      'minato fumi',
      'sumiya',
      'ishikawa shisuke',
      'shono kotaro',
      'azuma ran',
      //
      'misagi nagomu',
      'inuburo',
      'bosshi',
      'e-musu aki',
      'koume keito',
      'itou eight',
      'higenamuchi',
      'namboku',
      //
      'azuma tesshin',
      'bareisho',
      'pon takahanada',
      'onda chiro',
      'hachiya makoto',
      'naruko hanaharu',
      'linda',
      'miyabi tsuzuru',
      'mg joe',
      'nishi iori',
    ],
    {'default': 'COMIC X-EROS', 'ko': '코믹 제로스'}: [
      'distance',
      'yonekura kengo',
      'tsukino jyogi',
      'fuetakishi',
      'ishikei',
      'oda non',
      'takayaki',
      'knuckle curve',
      'hisakawa tinn',
      'makinosaka shinichi',
      'kuronomiki',
      'akino sora',
      'gomennasai',
      'sasayuki',
      '23',
      'shindol',
      'kurosaki rendou',
      'hiyoshi hana',
      'yarii shimeta',
      'shinonome ryu',
      'yoshida inuhito',
      'hori hiroaki',
    ],
    {'default': 'Pure Love', 'ko': '순애', 'ja': '純愛', 'zh': '爱'}: [
      "ichimatsu",
      "e-musu aki",
      "fujimaru",
      "hinasaki yo",
      "suihei sen",
      "momoko",
      "kizuka kazuki",
      "doumou",
      "katsurai yoshiaki",
      "hiten",
      "emily",
      "john k. pe-ta",
      "botan mochito",
      "meme50",
      "tomohiro kai",
      "sanjuurou",
      "yamada yuuya",
      "umakuchi_shouyu",
      "azuma tesshin",
      "meganei",
      "goban",
      "homunculus",
      "kamizuki shiki",
      "kotengu",
      "key",
      "ikuhana niro",
      "thikiso takeda",
      "kyockcho",
      "hamao",
      "mikuni_mizuki",
      "otabe sakura",
      "regdic",
      "akagi_asahito",
      "michiking",
      "pyon-kti",
      "kakao",
      "hinahara_emi",
    ],
    {'default': 'Loli', 'ko': '로리'}: [
      'quzila',
      'mochi',
      'asanagi',
      "tanabe kyou",
      "tamagoro",
      "azuma sawayoshi",
      "kinnotama",
      "mitsudoue",
      "yone kinji",
      'dancyo',
      'kiya shii',
      'henreader',
      "misao.",
      "ohisashiburi",
      'kanyapyi',
      'yukiu con',
      'haguhagu',
      'maki',
      'hisasi',
      'noise',
      'kinku',
      'okada kou',
      'atage',
      'miwa futaba',
      'mamezou',
      'ichihaya',
      'tanaka decilitre',
      'kannazuki motofumi',
      'panbai',
      'fuyuno mikan',
      'gengorou',
      'shouji ayumu',
      'rico',
      'shimanto shisakugata',
      'yuizaki kazuya',
      'tamano kedama',
      "urajirou",
      'shirane taito',
      'usashiro mani',
      'gomennasai',
      'sekiya asami',
      'inuboshi',
      'higashiyama show',
    ],
    {'default': 'Oneshota', 'ko': '오네쇼타'}: [
      "morishima kon",
      "tachibana omina",
    ],
    {'default': 'Femdom'}: [
      "hiroe rei",
      "takei ooki",
      "parabola",
      "2t",
      "akai mato",
      "mame",
      "oouso",
      "shindou",
      "hanabi",
    ],
    {'default': 'Netorare', 'ko': '네토라레'}: [
      "pija",
      "taniguchi-san",
      "fuuga",
      "shimanto shisakugata",
      "akitsuki itsuki",
      "mizutani tooru",
    ],

    //
    //  Effeminate
    //
    {'default': 'Shota'}: [],

    //
    //  Gay
    //
    {'default': 'Gay'}: [
      "tagame gengoroh",
    ],

    //
    //  Minor
    //
    {'default': 'BDSM'}: [],
    {'default': 'Insect'}: [],
  };
}
